<a href="https://colab.research.google.com/github/sanyam092006/ml_new/blob/main/Copy_of_IMDb_Week_Long_Pandas_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from google.colab import drive
drive.mount('/content/drive')
fil="/content/drive/MyDrive/imdb_data.csv"

Mounted at /content/drive

# IMDb Dataset - Assignment

Complete all questions during the week. Write your solutions below each question.

### Question 1
Load the IMDb dataset using Pandas.

In [4]:
# Write your solution here
import pandas as pd
# from google.colab import drive
# drive.mount('/content/drive')
fil="/content/drive/MyDrive/imdb_data.csv"
df=pd.read_csv(fil)
df

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,2/20/15,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,8/6/04,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,10/10/14,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,3/9/12,122.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,2/5/09,118.0,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,2996,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",NaN,tt0109403,en,Chasers,Military men Rock Reilly and Eddie Devane are ...,9.853270,...,4/22/94,102.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It was supposed to be a routine prisoner trans...,Chasers,"[{'id': 378, 'name': 'prison'}, {'id': 572, 'n...","[{'cast_id': 2, 'character': 'Rock Reilly', 'c...","[{'credit_id': '52fe4494c3a368484e02ac7d', 'de...",1596687
2996,2997,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...",NaN,tt2364975,sv,Vi är bäst!,Three girls in 1980s Stockholm decide to form ...,3.727996,...,3/28/13,102.0,"[{'iso_639_1': 'sv', 'name': 'svenska'}]",Released,NaN,We Are the Best!,"[{'id': 1192, 'name': 'sweden'}, {'id': 4470, ...","[{'cast_id': 5, 'character': 'Bobo', 'credit_i...","[{'credit_id': '5716b72ac3a3686678012c84', 'de...",180590
2997,2998,NaN,65000000,"[{'id': 80, 'name': 'Crime'}, {'id': 28, 'name...",NaN,tt0116908,en,The Long Kiss Goodnight,"Samantha Caine, suburban homemaker, is the ide...",14.482345,...,10/11/96,120.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,What's forgotten is not always gone.,The Long Kiss Goodnight,"[{'id': 441, 'name': 'assassination'}, {'id': ...","[{'cast_id': 10, 'character': 'Samantha Caine ...","[{'credit_id': '52fe443a9251416c7502d579', 'de...",89456761
2998,2999,NaN,42000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",http://www.alongcamepolly.com/,tt0343135,en,Along Came Polly,Reuben Feffer is a guy who's spent his entire ...,15.725542,...,1/16/04,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"For the most cautious man on Earth, life is ab...",Along Came Polly,"[{'id': 966, 'name': 'beach'}, {'id': 2676, 'n...","[{'cast_id': 8, 'character': 'Reuben Feffer', ...","[{'credit_id': '556f817b9251410866000a63', 'de...",171963386
2999,3000,NaN,35000000,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",http://www.abductionthefilm.com/,tt1600195,en,Abduction,A young man sets out to uncover the truth abou...,10.512109,...,9/22/11,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,They stole his life. He's taking it back.,Abduction,"[{'id': 591, 'name': 'cia'}, {'id': 822, 'name...","[{'cast_id': 2, 'character': 'Nathan Harper', ...","[{'credit_id': '5391990d0e0a260fb5001629', 'de...",82087155

### Question 2
Display the first 10 rows of the dataset.

In [5]:
# Write your solution here
import pandas as pd
# from google.colab import drive
# drive.mount('/content/drive')
fil="/content/drive/MyDrive/imdb_data.csv"
df=pd.read_csv(fil)
print(df.head(10))

   id                              belongs_to_collection    budget  \
0   1  [{'id': 313576, 'name': 'Hot Tub Time Machine ...  14000000
1   2  [{'id': 107674, 'name': 'The Princess Diaries ...  40000000
2   3                                                NaN   3300000
3   4                                                NaN   1200000
4   5                                                NaN         0
5   6                                                NaN   8000000
6   7                                                NaN  14000000
7   8                                                NaN         0
8   9  [{'id': 256377, 'name': 'The Muppet Collection...         0
9  10                                                NaN   6000000

                                              genres  \
0                     [{'id': 35, 'name': 'Comedy'}]
1  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
2                      [{'id': 18, 'name': 'Drama'}]
3  [{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...
4  [{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...
5  [{'id': 16, 'name': 'Animation'}, {'id': 12, '...
6  [{'id': 27, 'name': 'Horror'}, {'id': 53, 'nam...
7                [{'id': 99, 'name': 'Documentary'}]
8  [{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...
9  [{'id': 35, 'name': 'Comedy'}, {'id': 10402, '...

                             homepage    imdb_id original_language  \
0                                 NaN  tt2637294                en
1                                 NaN  tt0368933                en
2   http://sonyclassics.com/whiplash/  tt2582802                en
3          http://kahaanithefilm.com/  tt1821480                hi
4                                 NaN  tt1380152                ko
5                                 NaN  tt0093743                en
6  http://www.thepossessionmovie.com/  tt0431021                en
7                                 NaN  tt0391024                en
8                                 NaN  tt0117110                en
9                                 NaN  tt0310281                en

                             original_title  \
0                    Hot Tub Time Machine 2
1  The Princess Diaries 2: Royal Engagement
2                                  Whiplash
3                                   Kahaani
4                                      마린보이
5    Pinocchio and the Emperor of the Night
6                            The Possession
7                              Control Room
8                    Muppet Treasure Island
9                             A Mighty Wind

                                            overview  popularity  ...  \
0  When Lou, who has become the "father of the In...    6.575393  ...
1  Mia Thermopolis is now a college graduate and ...    8.248895  ...
2  Under the direction of a ruthless instructor, ...   64.299990  ...
3  Vidya Bagchi (Vidya Balan) arrives in Kolkata ...    3.174936  ...
4  Marine Boy is the story of a former national s...    1.148070  ...
5  Pinocchio and his friends, a glow worm and a m...    0.743274  ...
6  A young girl buys an antique box at a yard sal...    7.286477  ...
7  A chronicle which provides a rare window into ...    1.949044  ...
8  After telling the story of Flint's last journe...    6.902423  ...
9  In "A Mighty Wind", director Christopher Guest...    4.672036  ...

  release_date runtime                                   spoken_languages  \
0      2/20/15    93.0           [{'iso_639_1': 'en', 'name': 'English'}]
1       8/6/04   113.0           [{'iso_639_1': 'en', 'name': 'English'}]
2     10/10/14   105.0           [{'iso_639_1': 'en', 'name': 'English'}]
3       3/9/12   122.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
4       2/5/09   118.0           [{'iso_639_1': 'ko', 'name': '한국어/조선말'}]
5       8/6/87    83.0           [{'iso_639_1': 'en', 'name': 'English'}]
6      8/30/12    92.0           [{'iso_639_1': 'en', 'name': 'English'}]
7      1/15/04    84.0  [{'iso_639_1': 'ar', 'name': 'العربية'}, {'iso...
8      2/16/96   100.0           [{'iso_639_1': 'en', 'name': 'English'}]
9      4/16/03    91.0           [{'iso_639_1': 'en', 'name': 'English'}]

     status                                            tagline  \
0  Released  The Laws of Space and Time are About to be Vio...
1  Released  It can take a lifetime to find true love; she'...
2  Released    The road to greatness can take you to the edge.
3  Released                                                NaN
4  Released                                                NaN
5  Released                                                NaN
6  Released               Fear The Demon That Doesn't Fear God
7  Released              Different channels. Different truths.
8  Released                        Set sail for Muppet mayhem!
9  Released           Back together for the first time, again.

                                      title  \
0                    Hot Tub Time Machine 2
1  The Princess Diaries 2: Royal Engagement
2                                  Whiplash
3                                   Kahaani
4                                Marine Boy
5    Pinocchio and the Emperor of the Night
6                            The Possession
7                              Control Room
8                    Muppet Treasure Island
9                             A Mighty Wind

                                            Keywords  \
0  [{'id': 4379, 'name': 'time travel'}, {'id': 9...
1  [{'id': 2505, 'name': 'coronation'}, {'id': 42...
2  [{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...
3  [{'id': 10092, 'name': 'mystery'}, {'id': 1054...
4                                                NaN
5                                                NaN
6                                                NaN
7  [{'id': 917, 'name': 'journalism'}, {'id': 163...
8  [{'id': 2041, 'name': 'island'}, {'id': 4418, ...
9  [{'id': 11800, 'name': 'mockumentary'}, {'id':...

                                                cast  \
0  [{'cast_id': 4, 'character': 'Lou', 'credit_id...
1  [{'cast_id': 1, 'character': 'Mia Thermopolis'...
2  [{'cast_id': 5, 'character': 'Andrew Neimann',...
3  [{'cast_id': 1, 'character': 'Vidya Bagchi', '...
4  [{'cast_id': 3, 'character': 'Chun-soo', 'cred...
5  [{'cast_id': 6, 'character': 'Pinocchio (voice...
6  [{'cast_id': 23, 'character': 'Clyde', 'credit...
7  [{'cast_id': 2, 'character': 'Himself', 'credi...
8  [{'cast_id': 1, 'character': 'Long John Silver...
9  [{'cast_id': 24, 'character': 'Jonathan Steinb...

                                                crew   revenue
0  [{'credit_id': '59ac067c92514107af02c8c8', 'de...  12314651
1  [{'credit_id': '52fe43fe9251416c7502563d', 'de...  95149435
2  [{'credit_id': '54d5356ec3a3683ba0000039', 'de...  13092000
3  [{'credit_id': '52fe48779251416c9108d6eb', 'de...  16000000
4  [{'credit_id': '52fe464b9251416c75073b43', 'de...   3923970
5  [{'credit_id': '52fe46f49251416c9106558b', 'de...   3261638
6  [{'credit_id': '52fe4981c3a368484e12ee29', 'de...  85446075
7  [{'credit_id': '52fe47a69251416c750a0daf', 'de...   2586511
8  [{'credit_id': '52fe43c89251416c7501deb3', 'de...  34327391
9  [{'credit_id': '52fe45609251416c750545b3', 'de...  18750246

[10 rows x 23 columns]

### Question 3
Display the last 10 rows of the dataset.

In [6]:
import pandas as pd
# from google.colab import drive
# drive.mount('/content/drive')
fil="/content/drive/MyDrive/imdb_data.csv"
df=pd.read_csv(fil)
print(df.tail(10))

        id                              belongs_to_collection    budget  \
2990  2991                                                NaN         0
2991  2992  [{'id': 107469, 'name': 'Save The Last Dance C...  13000000
2992  2993                                                NaN   1135654
2993  2994                                                NaN  60000000
2994  2995                                                NaN         0
2995  2996                                                NaN         0
2996  2997                                                NaN         0
2997  2998                                                NaN  65000000
2998  2999                                                NaN  42000000
2999  3000                                                NaN  35000000

                                                 genres  \
2990  [{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...
2991  [{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...
2992  [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...
2993  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
2994                      [{'id': 18, 'name': 'Drama'}]
2995  [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...
2996  [{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...
2997  [{'id': 80, 'name': 'Crime'}, {'id': 28, 'name...
2998  [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...
2999  [{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...

                                  homepage    imdb_id original_language  \
2990                                   NaN  tt0118663                en
2991                                   NaN  tt0206275                en
2992                                   NaN  tt0015400                en
2993  http://www.theterminal-themovie.com/  tt0362227                en
2994                                   NaN  tt0105327                en
2995                                   NaN  tt0109403                en
2996                                   NaN  tt2364975                sv
2997                                   NaN  tt0116908                en
2998        http://www.alongcamepolly.com/  tt0343135                en
2999      http://www.abductionthefilm.com/  tt1600195                en

               original_title  \
2990                 B.A.P.S.
2991      Save the Last Dance
2992      The Thief of Bagdad
2993             The Terminal
2994              School Ties
2995                  Chasers
2996              Vi är bäst!
2997  The Long Kiss Goodnight
2998         Along Came Polly
2999                Abduction

                                               overview  popularity  ...  \
2990  Can two clueless Georgia homegirls with big he...    1.560980  ...
2991  A white midwestern girl moves to Chicago, wher...    4.794088  ...
2992  A recalcitrant thief vies with a duplicitous M...    3.878515  ...
2993  Viktor Navorski is a man without a country; hi...   14.092373  ...
2994  When David Greene receives a football scholars...    7.438381  ...
2995  Military men Rock Reilly and Eddie Devane are ...    9.853270  ...
2996  Three girls in 1980s Stockholm decide to form ...    3.727996  ...
2997  Samantha Caine, suburban homemaker, is the ide...   14.482345  ...
2998  Reuben Feffer is a guy who's spent his entire ...   15.725542  ...
2999  A young man sets out to uncover the truth abou...   10.512109  ...

     release_date runtime                                   spoken_languages  \
2990      3/28/97    90.0           [{'iso_639_1': 'en', 'name': 'English'}]
2991      1/12/01   112.0           [{'iso_639_1': 'en', 'name': 'English'}]
2992      3/18/24   149.0       [{'iso_639_1': 'xx', 'name': 'No Language'}]
2993      6/17/04   128.0  [{'iso_639_1': 'bg', 'name': 'български език'}...
2994      9/18/92   106.0           [{'iso_639_1': 'en', 'name': 'English'}]
2995      4/22/94   102.0           [{'iso_639_1': 'en', 'name': 'English'}]
2996      3/28/13   102.0           [{'iso_639_1': 'sv', 'name': 'svenska'}]
2997     10/11/96   120.0           [{'iso_639_1': 'en', 'name': 'English'}]
2998      1/16/04    90.0           [{'iso_639_1': 'en', 'name': 'English'}]
2999      9/22/11   106.0           [{'iso_639_1': 'en', 'name': 'English'}]

        status                                            tagline  \
2990  Released                These Pretty Women... Are Clueless!
2991  Released        The Only Person You Need To Be Is Yourself.
2992  Released                         "Happiness Must Be Earned"
2993  Released                                   Life is waiting.
2994  Released  Just because you’re accepted doesn’t mean you ...
2995  Released  It was supposed to be a routine prisoner trans...
2996  Released                                                NaN
2997  Released               What's forgotten is not always gone.
2998  Released  For the most cautious man on Earth, life is ab...
2999  Released          They stole his life. He's taking it back.

                        title  \
2990                 B.A.P.S.
2991      Save the Last Dance
2992      The Thief of Bagdad
2993             The Terminal
2994              School Ties
2995                  Chasers
2996         We Are the Best!
2997  The Long Kiss Goodnight
2998         Along Came Polly
2999                Abduction

                                               Keywords  \
2990  [{'id': 1437, 'name': 'burglar'}, {'id': 1946,...
2991  [{'id': 4118, 'name': 'ballet dancer'}, {'id':...
2992  [{'id': 255, 'name': 'male nudity'}, {'id': 14...
2993  [{'id': 242, 'name': 'new york'}, {'id': 822, ...
2994  [{'id': 6075, 'name': 'sport'}, {'id': 10144, ...
2995  [{'id': 378, 'name': 'prison'}, {'id': 572, 'n...
2996  [{'id': 1192, 'name': 'sweden'}, {'id': 4470, ...
2997  [{'id': 441, 'name': 'assassination'}, {'id': ...
2998  [{'id': 966, 'name': 'beach'}, {'id': 2676, 'n...
2999  [{'id': 591, 'name': 'cia'}, {'id': 822, 'name...

                                                   cast  \
2990  [{'cast_id': 3, 'character': 'Nisi', 'credit_i...
2991  [{'cast_id': 18, 'character': 'Sara Johnson', ...
2992  [{'cast_id': 3, 'character': 'The Thief of Bag...
2993  [{'cast_id': 4, 'character': 'Viktor Navorski'...
2994  [{'cast_id': 2, 'character': 'David Greene', '...
2995  [{'cast_id': 2, 'character': 'Rock Reilly', 'c...
2996  [{'cast_id': 5, 'character': 'Bobo', 'credit_i...
2997  [{'cast_id': 10, 'character': 'Samantha Caine ...
2998  [{'cast_id': 8, 'character': 'Reuben Feffer', ...
2999  [{'cast_id': 2, 'character': 'Nathan Harper', ...

                                                   crew    revenue
2990  [{'credit_id': '52fe477b9251416c7509af57', 'de...    7240837
2991  [{'credit_id': '52fe4533c3a36847f80c1c6b', 'de...   91038276
2992  [{'credit_id': '52fe45bec3a368484e06c70b', 'de...    1213880
2993  [{'credit_id': '52fe4259c3a36847f8017699', 'de...  219417255
2994  [{'credit_id': '5637777ac3a3681b4d01f9f5', 'de...   14715067
2995  [{'credit_id': '52fe4494c3a368484e02ac7d', 'de...    1596687
2996  [{'credit_id': '5716b72ac3a3686678012c84', 'de...     180590
2997  [{'credit_id': '52fe443a9251416c7502d579', 'de...   89456761
2998  [{'credit_id': '556f817b9251410866000a63', 'de...  171963386
2999  [{'credit_id': '5391990d0e0a260fb5001629', 'de...   82087155

[10 rows x 23 columns]

### Question 4
Find the total number of rows and columns in the dataset.

In [7]:
# Write your solution here
import pandas as pd
# from google.colab import drive
# drive.mount('/content/drive')
fil="/content/drive/MyDrive/imdb_data.csv"
df=pd.read_csv(fil)
print(df.shape)

(3000, 23)

### Question 5
Display all column names.

In [8]:
# Write your solution here
import pandas as pd
# from google.colab import drive
# drive.mount('/content/drive')
fil="/content/drive/MyDrive/imdb_data.csv"
df=pd.read_csv(fil)
print(df.columns)

Index(['id', 'belongs_to_collection', 'budget', 'genres', 'homepage',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'runtime', 'spoken_languages',
       'status', 'tagline', 'title', 'Keywords', 'cast', 'crew', 'revenue'],
      dtype='object')

### Question 6
Check the data types of all columns.

In [9]:
import pandas as pd
# from google.colab import drive
# drive.mount('/content/drive')
fil="/content/drive/MyDrive/imdb_data.csv"
df=pd.read_csv(fil)
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     3000 non-null   int64
 1   belongs_to_collection  604 non-null    object
 2   budget                 3000 non-null   int64
 3   genres                 2993 non-null   object
 4   homepage               946 non-null    object
 5   imdb_id                3000 non-null   object
 6   original_language      3000 non-null   object
 7   original_title         3000 non-null   object
 8   overview               2992 non-null   object
 9   popularity             3000 non-null   float64
 10  poster_path            2999 non-null   object
 11  production_companies   2844 non-null   object
 12  production_countries   2945 non-null   object
 13  release_date           3000 non-null   object
 14  runtime                2998 non-null   float64
 15  spoken_languages       2980 non-null   object
 16  status                 3000 non-null   object
 17  tagline                2403 non-null   object
 18  title                  3000 non-null   object
 19  Keywords               2724 non-null   object
 20  cast                   2987 non-null   object
 21  crew                   2984 non-null   object
 22  revenue                3000 non-null   int64
dtypes: float64(2), int64(3), object(18)
memory usage: 539.2+ KB
None

### Question 7
Find the total number of missing values in each column.

In [10]:
# Write your solution here
print(df.isnull().sum())

id                          0
belongs_to_collection    2396
budget                      0
genres                      7
homepage                 2054
imdb_id                     0
original_language           0
original_title              0
overview                    8
popularity                  0
poster_path                 1
production_companies      156
production_countries       55
release_date                0
runtime                     2
spoken_languages           20
status                      0
tagline                   597
title                       0
Keywords                  276
cast                       13
crew                       16
revenue                     0
dtype: int64

### Question 8
Generate summary statistics using describe().

In [11]:
# Write your solution here
print(df.describe())

                id        budget   popularity      runtime       revenue
count  3000.000000  3.000000e+03  3000.000000  2998.000000  3.000000e+03
mean   1500.500000  2.253133e+07     8.463274   107.856571  6.672585e+07
std     866.169729  3.702609e+07    12.104000    22.086434  1.375323e+08
min       1.000000  0.000000e+00     0.000001     0.000000  1.000000e+00
25%     750.750000  0.000000e+00     4.018053    94.000000  2.379808e+06
50%    1500.500000  8.000000e+06     7.374861   104.000000  1.680707e+07
75%    2250.250000  2.900000e+07    10.890983   118.000000  6.891920e+07
max    3000.000000  3.800000e+08   294.337037   338.000000  1.519558e+09

### Question 1
Display rows 10 to 20 and columns 2 to 5 using iloc.

In [12]:
# Write your solution here
print(df.iloc[10:21,2:6])

       budget                                             genres  \
10    1000000                      [{'id': 18, 'name': 'Drama'}]
11          0                     [{'id': 35, 'name': 'Comedy'}]
12   15000000                      [{'id': 18, 'name': 'Drama'}]
13   53000000  [{'id': 35, 'name': 'Comedy'}, {'id': 80, 'nam...
14  102000000  [{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...
15     500000  [{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...
16   26000000  [{'id': 27, 'name': 'Horror'}, {'id': 53, 'nam...
17          0  [{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...
18    8000000  [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...
19   32000000  [{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...
20   80000000  [{'id': 12, 'name': 'Adventure'}, {'id': 10751...

                                 homepage    imdb_id
10                                    NaN  tt0075148
11                                    NaN  tt0093857
12          http://www.dreamworks.com/ab/  tt0169547
13                                    NaN  tt0377471
14                                    NaN  tt0181689
15  http://skinningmovie.com/synopsis.htm  tt1129437
16                                    NaN  tt0421239
17                                    NaN  tt1700845
18                                    NaN  tt1487118
19                                    NaN  tt0388482
20                                    NaN  tt0120738

### Question 2
Display the first 15 rows using iloc.

In [13]:
# Write your solution here
print(df.iloc[:15,:])

    id                              belongs_to_collection     budget  \
0    1  [{'id': 313576, 'name': 'Hot Tub Time Machine ...   14000000
1    2  [{'id': 107674, 'name': 'The Princess Diaries ...   40000000
2    3                                                NaN    3300000
3    4                                                NaN    1200000
4    5                                                NaN          0
5    6                                                NaN    8000000
6    7                                                NaN   14000000
7    8                                                NaN          0
8    9  [{'id': 256377, 'name': 'The Muppet Collection...          0
9   10                                                NaN    6000000
10  11  [{'id': 1575, 'name': 'Rocky Collection', 'pos...    1000000
11  12  [{'id': 48190, 'name': 'Revenge of the Nerds C...          0
12  13                                                NaN   15000000
13  14  [{'id': 91698, 'name': 'Chili Palmer Collectio...   53000000
14  15                                                NaN  102000000

                                               genres  \
0                      [{'id': 35, 'name': 'Comedy'}]
1   [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
2                       [{'id': 18, 'name': 'Drama'}]
3   [{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...
4   [{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...
5   [{'id': 16, 'name': 'Animation'}, {'id': 12, '...
6   [{'id': 27, 'name': 'Horror'}, {'id': 53, 'nam...
7                 [{'id': 99, 'name': 'Documentary'}]
8   [{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...
9   [{'id': 35, 'name': 'Comedy'}, {'id': 10402, '...
10                      [{'id': 18, 'name': 'Drama'}]
11                     [{'id': 35, 'name': 'Comedy'}]
12                      [{'id': 18, 'name': 'Drama'}]
13  [{'id': 35, 'name': 'Comedy'}, {'id': 80, 'nam...
14  [{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...

                              homepage    imdb_id original_language  \
0                                  NaN  tt2637294                en
1                                  NaN  tt0368933                en
2    http://sonyclassics.com/whiplash/  tt2582802                en
3           http://kahaanithefilm.com/  tt1821480                hi
4                                  NaN  tt1380152                ko
5                                  NaN  tt0093743                en
6   http://www.thepossessionmovie.com/  tt0431021                en
7                                  NaN  tt0391024                en
8                                  NaN  tt0117110                en
9                                  NaN  tt0310281                en
10                                 NaN  tt0075148                en
11                                 NaN  tt0093857                en
12       http://www.dreamworks.com/ab/  tt0169547                en
13                                 NaN  tt0377471                en
14                                 NaN  tt0181689                en

                                original_title  \
0                       Hot Tub Time Machine 2
1     The Princess Diaries 2: Royal Engagement
2                                     Whiplash
3                                      Kahaani
4                                         마린보이
5       Pinocchio and the Emperor of the Night
6                               The Possession
7                                 Control Room
8                       Muppet Treasure Island
9                                A Mighty Wind
10                                       Rocky
11  Revenge of the Nerds II: Nerds in Paradise
12                             American Beauty
13                                     Be Cool
14                             Minority Report

                                             overview  popularity  ...  \
0   When Lou, who has become the "father of the In...    6.575393  ...
1   Mia Thermopolis is now a college graduate and ...    8.248895  ...
2   Under the direction of a ruthless instructor, ...   64.299990  ...
3   Vidya Bagchi (Vidya Balan) arrives in Kolkata ...    3.174936  ...
4   Marine Boy is the story of a former national s...    1.148070  ...
5   Pinocchio and his friends, a glow worm and a m...    0.743274  ...
6   A young girl buys an antique box at a yard sal...    7.286477  ...
7   A chronicle which provides a rare window into ...    1.949044  ...
8   After telling the story of Flint's last journe...    6.902423  ...
9   In "A Mighty Wind", director Christopher Guest...    4.672036  ...
10  When world heavyweight boxing champion, Apollo...   14.774066  ...
11  The members of the Lambda Lambda Lambda frater...   10.543750  ...
12  Lester Burnham, a depressed suburban father in...   20.726578  ...
13  Disenchanted with the movie industry, Chili Pa...   13.314233  ...
14  John Anderton is a top 'Precrime' cop in the l...   20.666063  ...

   release_date runtime                                   spoken_languages  \
0       2/20/15    93.0           [{'iso_639_1': 'en', 'name': 'English'}]
1        8/6/04   113.0           [{'iso_639_1': 'en', 'name': 'English'}]
2      10/10/14   105.0           [{'iso_639_1': 'en', 'name': 'English'}]
3        3/9/12   122.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
4        2/5/09   118.0           [{'iso_639_1': 'ko', 'name': '한국어/조선말'}]
5        8/6/87    83.0           [{'iso_639_1': 'en', 'name': 'English'}]
6       8/30/12    92.0           [{'iso_639_1': 'en', 'name': 'English'}]
7       1/15/04    84.0  [{'iso_639_1': 'ar', 'name': 'العربية'}, {'iso...
8       2/16/96   100.0           [{'iso_639_1': 'en', 'name': 'English'}]
9       4/16/03    91.0           [{'iso_639_1': 'en', 'name': 'English'}]
10     11/21/76   119.0           [{'iso_639_1': 'en', 'name': 'English'}]
11      7/10/87    98.0           [{'iso_639_1': 'en', 'name': 'English'}]
12      9/15/99   122.0           [{'iso_639_1': 'en', 'name': 'English'}]
13       3/4/05   118.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
14      6/20/02   145.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...

      status                                            tagline  \
0   Released  The Laws of Space and Time are About to be Vio...
1   Released  It can take a lifetime to find true love; she'...
2   Released    The road to greatness can take you to the edge.
3   Released                                                NaN
4   Released                                                NaN
5   Released                                                NaN
6   Released               Fear The Demon That Doesn't Fear God
7   Released              Different channels. Different truths.
8   Released                        Set sail for Muppet mayhem!
9   Released           Back together for the first time, again.
10  Released          His whole life was a million-to-one shot.
11  Released                                      They're Back!
12  Released                                       Look closer.
13  Released           Everyone is looking for the next big hit
14  Released    The system is perfect until it comes after you.

                                         title  \
0                       Hot Tub Time Machine 2
1     The Princess Diaries 2: Royal Engagement
2                                     Whiplash
3                                      Kahaani
4                                   Marine Boy
5       Pinocchio and the Emperor of the Night
6                               The Possession
7                                 Control Room
8                       Muppet Treasure Island
9                                A Mighty Wind
10                                       Rocky
11  Revenge of the Nerds II: Nerds in Paradise
12                             American Beauty
13                                     Be Cool
14                             Minority Report

                                             Keywords  \
0   [{'id': 4379, 'name': 'time travel'}, {'id': 9...
1   [{'id': 2505, 'name': 'coronation'}, {'id': 42...
2   [{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...
3   [{'id': 10092, 'name': 'mystery'}, {'id': 1054...
4                                                 NaN
5                                                 NaN
6                                                 NaN
7   [{'id': 917, 'name': 'journalism'}, {'id': 163...
8   [{'id': 2041, 'name': 'island'}, {'id': 4418, ...
9   [{'id': 11800, 'name': 'mockumentary'}, {'id':...
10  [{'id': 240, 'name': 'underdog'}, {'id': 276, ...
11  [{'id': 5801, 'name': 'nerd'}, {'id': 6876, 'n...
12  [{'id': 255, 'name': 'male nudity'}, {'id': 29...
13  [{'id': 3605, 'name': 'baseball bat'}, {'id': ...
14  [{'id': 476, 'name': 'self-fulfilling prophecy...

                                                 cast  \
0   [{'cast_id': 4, 'character': 'Lou', 'credit_id...
1   [{'cast_id': 1, 'character': 'Mia Thermopolis'...
2   [{'cast_id': 5, 'character': 'Andrew Neimann',...
3   [{'cast_id': 1, 'character': 'Vidya Bagchi', '...
4   [{'cast_id': 3, 'character': 'Chun-soo', 'cred...
5   [{'cast_id': 6, 'character': 'Pinocchio (voice...
6   [{'cast_id': 23, 'character': 'Clyde', 'credit...
7   [{'cast_id': 2, 'character': 'Himself', 'credi...
8   [{'cast_id': 1, 'character': 'Long John Silver...
9   [{'cast_id': 24, 'character': 'Jonathan Steinb...
10  [{'cast_id': 16, 'character': 'Rocky Balboa', ...
11  [{'cast_id': 2, 'character': 'Lewis Skolnick',...
12  [{'cast_id': 6, 'character': 'Lester Burnham',...
13  [{'cast_id': 4, 'character': 'Chili Palmer', '...
14  [{'cast_id': 5, 'character': 'Chief John Ander...

                                                 crew    revenue
0   [{'credit_id': '59ac067c92514107af02c8c8', 'de...   12314651
1   [{'credit_id': '52fe43fe9251416c7502563d', 'de...   95149435
2   [{'credit_id': '54d5356ec3a3683ba0000039', 'de...   13092000
3   [{'credit_id': '52fe48779251416c9108d6eb', 'de...   16000000
4   [{'credit_id': '52fe464b9251416c75073b43', 'de...    3923970
5   [{'credit_id': '52fe46f49251416c9106558b', 'de...    3261638
6   [{'credit_id': '52fe4981c3a368484e12ee29', 'de...   85446075
7   [{'credit_id': '52fe47a69251416c750a0daf', 'de...    2586511
8   [{'credit_id': '52fe43c89251416c7501deb3', 'de...   34327391
9   [{'credit_id': '52fe45609251416c750545b3', 'de...   18750246
10  [{'credit_id': '579948e9c3a36874e9007b0b', 'de...  117235147
11  [{'credit_id': '52fe46f49251416c750891e9', 'de...   22642033
12  [{'credit_id': '52fe420ec3a36847f80007c5', 'de...  356296601
13  [{'credit_id': '52fe43cbc3a36847f807039f', 'de...   95226116
14  [{'credit_id': '52fe4223c3a36847f8006f3d', 'de...  358372926

[15 rows x 23 columns]

### Question 3
Extract only the columns: title, budget, revenue using loc.

In [14]:
# Write your solution here
print(df.loc[:,['original_title','budget','revenue']])

                                original_title    budget    revenue
0                       Hot Tub Time Machine 2  14000000   12314651
1     The Princess Diaries 2: Royal Engagement  40000000   95149435
2                                     Whiplash   3300000   13092000
3                                      Kahaani   1200000   16000000
4                                         마린보이         0    3923970
...                                        ...       ...        ...
2995                                   Chasers         0    1596687
2996                               Vi är bäst!         0     180590
2997                   The Long Kiss Goodnight  65000000   89456761
2998                          Along Came Polly  42000000  171963386
2999                                 Abduction  35000000   82087155

[3000 rows x 3 columns]

### Question 4
Display only the title and runtime columns.

In [15]:
# Write your solution here
import pandas as pd
# from google.colab import drive
# drive.mount('/content/drive')
fil="/content/drive/MyDrive/imdb_data.csv"
df=pd.read_csv(fil)

print(df.loc[:,['original_title','runtime']])

                                original_title  runtime
0                       Hot Tub Time Machine 2     93.0
1     The Princess Diaries 2: Royal Engagement    113.0
2                                     Whiplash    105.0
3                                      Kahaani    122.0
4                                         마린보이    118.0
...                                        ...      ...
2995                                   Chasers    102.0
2996                               Vi är bäst!    102.0
2997                   The Long Kiss Goodnight    120.0
2998                          Along Came Polly     90.0
2999                                 Abduction    106.0

[3000 rows x 2 columns]

### Question 5
Extract the last 20 rows of the dataset.

In [16]:
# Write your solution here
print(df.tail(20))

        id                              belongs_to_collection    budget  \
2980  2981                                                NaN    300000
2981  2982                                                NaN         0
2982  2983                                                NaN    500000
2983  2984                                                NaN  35000000
2984  2985  [{'id': 221111, 'name': 'S.W.A.T. Collection',...  80000000
2985  2986                                                NaN  37665000
2986  2987                                                NaN  20000000
2987  2988                                                NaN         0
2988  2989                                                NaN         0
2989  2990                                                NaN         0
2990  2991                                                NaN         0
2991  2992  [{'id': 107469, 'name': 'Save The Last Dance C...  13000000
2992  2993                                                NaN   1135654
2993  2994                                                NaN  60000000
2994  2995                                                NaN         0
2995  2996                                                NaN         0
2996  2997                                                NaN         0
2997  2998                                                NaN  65000000
2998  2999                                                NaN  42000000
2999  3000                                                NaN  35000000

                                                 genres  \
2980  [{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...
2981                      [{'id': 18, 'name': 'Drama'}]
2982                      [{'id': 18, 'name': 'Drama'}]
2983  [{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...
2984  [{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...
2985  [{'id': 18, 'name': 'Drama'}, {'id': 53, 'name...
2986  [{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...
2987  [{'id': 27, 'name': 'Horror'}, {'id': 878, 'na...
2988                      [{'id': 18, 'name': 'Drama'}]
2989  [{'id': 16, 'name': 'Animation'}, {'id': 10751...
2990  [{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...
2991  [{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...
2992  [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...
2993  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
2994                      [{'id': 18, 'name': 'Drama'}]
2995  [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...
2996  [{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...
2997  [{'id': 80, 'name': 'Crime'}, {'id': 28, 'name...
2998  [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...
2999  [{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...

                                               homepage    imdb_id  \
2980           https://www.facebook.com/Actionherobiju/  tt5320514
2981                                                NaN  tt4158876
2982                                                NaN  tt2063781
2983                                                NaN  tt0118623
2984        http://www.sonypictures.com/homevideo/swat/  tt0257076
2985  http://www.sonypictures.com/homevideo/freedoml...  tt0349467
2986                                                NaN  tt0338325
2987                                                NaN  tt0096246
2988                                                NaN  tt0301978
2989                                                NaN  tt0206367
2990                                                NaN  tt0118663
2991                                                NaN  tt0206275
2992                                                NaN  tt0015400
2993               http://www.theterminal-themovie.com/  tt0362227
2994                                                NaN  tt0105327
2995                                                NaN  tt0109403
2996                                                NaN  tt2364975
2997                                                NaN  tt0116908
2998                     http://www.alongcamepolly.com/  tt0343135
2999                   http://www.abductionthefilm.com/  tt1600195

     original_language           original_title  \
2980                ml          ആക്ഷൻ ഹീറോ ബിജു
2981                en             Other People
2982                en                  Smashed
2983                en            Anna Karenina
2984                en                 S.W.A.T.
2985                en              Freedomland
2986                en                Paparazzi
2987                en        The Terror Within
2988                fa                       ده
2989                en  The Trumpet Of The Swan
2990                en                 B.A.P.S.
2991                en      Save the Last Dance
2992                en      The Thief of Bagdad
2993                en             The Terminal
2994                en              School Ties
2995                en                  Chasers
2996                sv              Vi är bäst!
2997                en  The Long Kiss Goodnight
2998                en         Along Came Polly
2999                en                Abduction

                                               overview  popularity  ...  \
2980  Biju is an honest policeman who fights the inj...    0.350207  ...
2981  David, a struggling comedy writer fresh off fr...    3.069108  ...
2982  Kate and Charlie like to have a good time. The...    4.893812  ...
2983  Anna (Marceau) is a wife and mother who has an...    5.660835  ...
2984  Hondo Harrelson recruits Jim Street to join an...   13.334952  ...
2985  A black police detective must solve a strange ...    5.388535  ...
2986  A rising Hollywood actor decides to take perso...   12.553403  ...
2987  Experiments in biological warfare have destroy...    1.292125  ...
2988  A visual social examination in the form of ten...    0.984515  ...
2989  The adventures of a young Trumpeter swan who c...    0.851599  ...
2990  Can two clueless Georgia homegirls with big he...    1.560980  ...
2991  A white midwestern girl moves to Chicago, wher...    4.794088  ...
2992  A recalcitrant thief vies with a duplicitous M...    3.878515  ...
2993  Viktor Navorski is a man without a country; hi...   14.092373  ...
2994  When David Greene receives a football scholars...    7.438381  ...
2995  Military men Rock Reilly and Eddie Devane are ...    9.853270  ...
2996  Three girls in 1980s Stockholm decide to form ...    3.727996  ...
2997  Samantha Caine, suburban homemaker, is the ide...   14.482345  ...
2998  Reuben Feffer is a guy who's spent his entire ...   15.725542  ...
2999  A young man sets out to uncover the truth abou...   10.512109  ...

     release_date runtime                                   spoken_languages  \
2980       2/4/16   144.0                  [{'iso_639_1': 'ml', 'name': ''}]
2981       9/9/16    97.0           [{'iso_639_1': 'en', 'name': 'English'}]
2982      9/12/12    85.0           [{'iso_639_1': 'en', 'name': 'English'}]
2983       4/4/97   108.0           [{'iso_639_1': 'en', 'name': 'English'}]
2984       8/8/03   117.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
2985      2/17/06   113.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
2986       9/3/04    84.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
2987      1/20/89    90.0           [{'iso_639_1': 'en', 'name': 'English'}]
2988      5/20/02    94.0             [{'iso_639_1': 'fa', 'name': 'فارسی'}]
2989      5/11/01    75.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
2990      3/28/97    90.0           [{'iso_639_1': 'en', 'name': 'English'}]
2991      1/12/01   112.0           [{'iso_639_1': 'en', 'name': 'English'}]
2992      3/18/24   149.0       [{'iso_639_1': 'xx', 'name': 'No Language'}]
2993      6/17/04   128.0  [{'iso_639_1': 'bg', 'name': 'български език'}...
2994      9/18/92   106.0           [{'iso_639_1': 'en', 'name': 'English'}]
2995      4/22/94   102.0           [{'iso_639_1': 'en', 'name': 'English'}]
2996      3/28/13   102.0           [{'iso_639_1': 'sv', 'name': 'svenska'}]
2997     10/11/96   120.0           [{'iso_639_1': 'en', 'name': 'English'}]
2998      1/16/04    90.0           [{'iso_639_1': 'en', 'name': 'English'}]
2999      9/22/11   106.0           [{'iso_639_1': 'en', 'name': 'English'}]

        status                                            tagline  \
2980  Released                       A ride with a police officer
2981  Released                                                NaN
2982  Released                                                NaN
2983  Released  In a world of power and privilege, one woman d...
2984  Released              You're either S.W.A.T. or you're not.
2985  Released    The Truth Is Hiding Where No One Dares To Look.
2986  Released                    One good shot deserves another.
2987  Released                               It Wants To Get Out!
2988  Released                                                NaN
2989  Released  Sometimes being different helps you to find yo...
2990  Released                These Pretty Women... Are Clueless!
2991  Released        The Only Person You Need To Be Is Yourself.
2992  Released                         "Happiness Must Be Earned"
2993  Released                                   Life is waiting.
2994  Released  Just because you’re accepted doesn’t mean you ...
2995  Released  It was supposed to be a routine prisoner trans...
2996  Released                                                NaN
2997  Released               What's forgotten is not always gone.
2998  Released  For the most cautious man on Earth, life is ab...
2999  Released          They stole his life. He's taking it back.

                        title  \
2980         Action Hero Biju
2981             Other People
2982                  Smashed
2983            Anna Karenina
2984                 S.W.A.T.
2985              Freedomland
2986                Paparazzi
2987        The Terror Within
2988                      Ten
2989  The Trumpet Of The Swan
2990                 B.A.P.S.
2991      Save the Last Dance
2992      The Thief of Bagdad
2993             The Terminal
2994              School Ties
2995                  Chasers
2996         We Are the Best!
2997  The Long Kiss Goodnight
2998         Along Came Polly
2999                Abduction

                                               Keywords  \
2980  [{'id': 1252, 'name': 'suicide attempt'}, {'id...
2981                [{'id': 234102, 'name': 'misfits'}]
2982                                                NaN
2983                                                NaN
2984  [{'id': 2434, 'name': 'liberation'}, {'id': 35...
2985  [{'id': 577, 'name': 'black people'}, {'id': 5...
2986        [{'id': 10183, 'name': 'independent film'}]
2987  [{'id': 1299, 'name': 'monster'}, {'id': 1852,...
2988  [{'id': 1156, 'name': 'sister sister relations...
2989  [{'id': 6653, 'name': 'trumpet'}, {'id': 10407...
2990  [{'id': 1437, 'name': 'burglar'}, {'id': 1946,...
2991  [{'id': 4118, 'name': 'ballet dancer'}, {'id':...
2992  [{'id': 255, 'name': 'male nudity'}, {'id': 14...
2993  [{'id': 242, 'name': 'new york'}, {'id': 822, ...
2994  [{'id': 6075, 'name': 'sport'}, {'id': 10144, ...
2995  [{'id': 378, 'name': 'prison'}, {'id': 572, 'n...
2996  [{'id': 1192, 'name': 'sweden'}, {'id': 4470, ...
2997  [{'id': 441, 'name': 'assassination'}, {'id': ...
2998  [{'id': 966, 'name': 'beach'}, {'id': 2676, 'n...
2999  [{'id': 591, 'name': 'cia'}, {'id': 822, 'name...

                                                   cast  \
2980  [{'cast_id': 1, 'character': 'Sub-Inspector Bi...
2981  [{'cast_id': 0, 'character': 'David', 'credit_...
2982  [{'cast_id': 1001, 'character': 'Kate Hannah',...
2983  [{'cast_id': 1, 'character': 'Anna Karenina', ...
2984  [{'cast_id': 25, 'character': "Sgt. Dan 'Hondo...
2985  [{'cast_id': 13, 'character': 'Lorenzo Council...
2986  [{'cast_id': 1, 'character': 'Bo Laramie', 'cr...
2987  [{'cast_id': 4, 'character': 'Hal', 'credit_id...
2988  [{'cast_id': 2, 'character': 'Driver', 'credit...
2989  [{'cast_id': 1, 'character': 'Father', 'credit...
2990  [{'cast_id': 3, 'character': 'Nisi', 'credit_i...
2991  [{'cast_id': 18, 'character': 'Sara Johnson', ...
2992  [{'cast_id': 3, 'character': 'The Thief of Bag...
2993  [{'cast_id': 4, 'character': 'Viktor Navorski'...
2994  [{'cast_id': 2, 'character': 'David Greene', '...
2995  [{'cast_id': 2, 'character': 'Rock Reilly', 'c...
2996  [{'cast_id': 5, 'character': 'Bobo', 'credit_i...
2997  [{'cast_id': 10, 'character': 'Samantha Caine ...
2998  [{'cast_id': 8, 'character': 'Reuben Feffer', ...
2999  [{'cast_id': 2, 'character': 'Nathan Harper', ...

                                                   crew    revenue
2980  [{'credit_id': '56b4d47f92514112b90045f6', 'de...    2500000
2981  [{'credit_id': '57d923309251415959005090', 'de...      93000
2982  [{'credit_id': '557455c1c3a3686b7d003df7', 'de...     376597
2983  [{'credit_id': '52fe47cac3a36847f81484f7', 'de...     791830
2984  [{'credit_id': '5379d4980e0a261431006f58', 'de...  116643346
2985  [{'credit_id': '52fe4551c3a36847f80c76e7', 'de...   14655628
2986  [{'credit_id': '5678044292514179dd008c37', 'de...   16605763
2987  [{'credit_id': '52fe45d9c3a368484e072511', 'de...     858591
2988  [{'credit_id': '52fe460a9251416c7506b0a7', 'de...     105656
2989  [{'credit_id': '58bc9d609251416084044b0e', 'de...     100202
2990  [{'credit_id': '52fe477b9251416c7509af57', 'de...    7240837
2991  [{'credit_id': '52fe4533c3a36847f80c1c6b', 'de...   91038276
2992  [{'credit_id': '52fe45bec3a368484e06c70b', 'de...    1213880
2993  [{'credit_id': '52fe4259c3a36847f8017699', 'de...  219417255
2994  [{'credit_id': '5637777ac3a3681b4d01f9f5', 'de...   14715067
2995  [{'credit_id': '52fe4494c3a368484e02ac7d', 'de...    1596687
2996  [{'credit_id': '5716b72ac3a3686678012c84', 'de...     180590
2997  [{'credit_id': '52fe443a9251416c7502d579', 'de...   89456761
2998  [{'credit_id': '556f817b9251410866000a63', 'de...  171963386
2999  [{'credit_id': '5391990d0e0a260fb5001629', 'de...   82087155

[20 rows x 23 columns]

### Question 6
Display rows 50 to 100 with only title and popularity columns.

In [17]:
# Write your solution here
print(df.loc[50:101,['original_title','popularity']])

                                       original_title  popularity
50                               Aanrijding in Moscou    1.572904
51                                     The Great Race    4.473327
52                      The Last Flight of Noah's Ark    1.012665
53                                          For Keeps    5.410839
54                                              Risen    8.759801
55                                         Son in Law    9.122718
56                                            Joueuse    2.947980
57                                     Batman & Robin   17.038824
58                                Were The World Mine    1.882446
59                            All About the Benjamins    3.909079
60                                      Casino Royale   23.065078
61                                            Trapeze    1.801071
62                                             Fallen    6.381612
63   Friday the 13th Part VIII: Jason Takes Manhattan    7.743144
64                                           Nebraska   11.160699
65                                         Bloodsport    8.822276
66                                      Henry's Crime    5.145185
67                                                天注定    6.303552
68                              To Kill a Mockingbird   14.284787
69              The Fast and the Furious: Tokyo Drift    2.238808
70                                         The Jacket   12.092096
71                             Diarios de motocicleta    7.667491
72                                           Cry-Baby    8.290384
73                                          Český sen    0.919556
74                                Jackson County Jail    2.482536
75                                       Fright Night    9.665251
76                          Kandukondain Kandukondain    0.660663
77                                         Caddyshack   10.451986
78                                   Sharky's Machine    2.633399
79                                                 31    6.636625
80                                          Dark Blue    4.984080
81                                           Shopgirl    4.349046
82                                   The Skeleton Key   10.947957
83                                               2010    7.482865
84                                       Silent House   10.239941
85                                              Congo    7.260574
86                                  Kramer vs. Kramer    9.741644
87                                                紅番區   12.314278
88                               The Zookeeper's Wife   13.655178
89                                          Sommersby    4.359884
90                                  Kill Bill: Vol. 1   25.261865
91                                  Le fate ignoranti    3.831960
92                             Le Hussard sur le toit    1.690768
93                                             Hunger   14.322814
94                                   Mulholland Drive   18.184056
95                         Со мною вот что происходит    0.181963
96                                       Nuit Blanche    2.942355
97                                             Mishen    1.042112
98                       Las aventuras de Tadeo Jones   11.003515
99                                             Colors    5.529808
100                                        Dark Angel    7.958502
101                                  A Beautiful Mind   11.936460

### Question 1
Find all movies whose original language is English (en).

In [18]:
# Write your solution here
print(df[df['original_language']=='en'])

        id                              belongs_to_collection    budget  \
0        1  [{'id': 313576, 'name': 'Hot Tub Time Machine ...  14000000
1        2  [{'id': 107674, 'name': 'The Princess Diaries ...  40000000
2        3                                                NaN   3300000
5        6                                                NaN   8000000
6        7                                                NaN  14000000
...    ...                                                ...       ...
2994  2995                                                NaN         0
2995  2996                                                NaN         0
2997  2998                                                NaN  65000000
2998  2999                                                NaN  42000000
2999  3000                                                NaN  35000000

                                                 genres  \
0                        [{'id': 35, 'name': 'Comedy'}]
1     [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
2                         [{'id': 18, 'name': 'Drama'}]
5     [{'id': 16, 'name': 'Animation'}, {'id': 12, '...
6     [{'id': 27, 'name': 'Horror'}, {'id': 53, 'nam...
...                                                 ...
2994                      [{'id': 18, 'name': 'Drama'}]
2995  [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...
2997  [{'id': 80, 'name': 'Crime'}, {'id': 28, 'name...
2998  [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...
2999  [{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...

                                homepage    imdb_id original_language  \
0                                    NaN  tt2637294                en
1                                    NaN  tt0368933                en
2      http://sonyclassics.com/whiplash/  tt2582802                en
5                                    NaN  tt0093743                en
6     http://www.thepossessionmovie.com/  tt0431021                en
...                                  ...        ...               ...
2994                                 NaN  tt0105327                en
2995                                 NaN  tt0109403                en
2997                                 NaN  tt0116908                en
2998      http://www.alongcamepolly.com/  tt0343135                en
2999    http://www.abductionthefilm.com/  tt1600195                en

                                original_title  \
0                       Hot Tub Time Machine 2
1     The Princess Diaries 2: Royal Engagement
2                                     Whiplash
5       Pinocchio and the Emperor of the Night
6                               The Possession
...                                        ...
2994                               School Ties
2995                                   Chasers
2997                   The Long Kiss Goodnight
2998                          Along Came Polly
2999                                 Abduction

                                               overview  popularity  ...  \
0     When Lou, who has become the "father of the In...    6.575393  ...
1     Mia Thermopolis is now a college graduate and ...    8.248895  ...
2     Under the direction of a ruthless instructor, ...   64.299990  ...
5     Pinocchio and his friends, a glow worm and a m...    0.743274  ...
6     A young girl buys an antique box at a yard sal...    7.286477  ...
...                                                 ...         ...  ...
2994  When David Greene receives a football scholars...    7.438381  ...
2995  Military men Rock Reilly and Eddie Devane are ...    9.853270  ...
2997  Samantha Caine, suburban homemaker, is the ide...   14.482345  ...
2998  Reuben Feffer is a guy who's spent his entire ...   15.725542  ...
2999  A young man sets out to uncover the truth abou...   10.512109  ...

     release_date runtime                          spoken_languages    status  \
0         2/20/15    93.0  [{'iso_639_1': 'en', 'name': 'English'}]  Released
1          8/6/04   113.0  [{'iso_639_1': 'en', 'name': 'English'}]  Released
2        10/10/14   105.0  [{'iso_639_1': 'en', 'name': 'English'}]  Released
5          8/6/87    83.0  [{'iso_639_1': 'en', 'name': 'English'}]  Released
6         8/30/12    92.0  [{'iso_639_1': 'en', 'name': 'English'}]  Released
...           ...     ...                                       ...       ...
2994      9/18/92   106.0  [{'iso_639_1': 'en', 'name': 'English'}]  Released
2995      4/22/94   102.0  [{'iso_639_1': 'en', 'name': 'English'}]  Released
2997     10/11/96   120.0  [{'iso_639_1': 'en', 'name': 'English'}]  Released
2998      1/16/04    90.0  [{'iso_639_1': 'en', 'name': 'English'}]  Released
2999      9/22/11   106.0  [{'iso_639_1': 'en', 'name': 'English'}]  Released

                                                tagline  \
0     The Laws of Space and Time are About to be Vio...
1     It can take a lifetime to find true love; she'...
2       The road to greatness can take you to the edge.
5                                                   NaN
6                  Fear The Demon That Doesn't Fear God
...                                                 ...
2994  Just because you’re accepted doesn’t mean you ...
2995  It was supposed to be a routine prisoner trans...
2997               What's forgotten is not always gone.
2998  For the most cautious man on Earth, life is ab...
2999          They stole his life. He's taking it back.

                                         title  \
0                       Hot Tub Time Machine 2
1     The Princess Diaries 2: Royal Engagement
2                                     Whiplash
5       Pinocchio and the Emperor of the Night
6                               The Possession
...                                        ...
2994                               School Ties
2995                                   Chasers
2997                   The Long Kiss Goodnight
2998                          Along Came Polly
2999                                 Abduction

                                               Keywords  \
0     [{'id': 4379, 'name': 'time travel'}, {'id': 9...
1     [{'id': 2505, 'name': 'coronation'}, {'id': 42...
2     [{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...
5                                                   NaN
6                                                   NaN
...                                                 ...
2994  [{'id': 6075, 'name': 'sport'}, {'id': 10144, ...
2995  [{'id': 378, 'name': 'prison'}, {'id': 572, 'n...
2997  [{'id': 441, 'name': 'assassination'}, {'id': ...
2998  [{'id': 966, 'name': 'beach'}, {'id': 2676, 'n...
2999  [{'id': 591, 'name': 'cia'}, {'id': 822, 'name...

                                                   cast  \
0     [{'cast_id': 4, 'character': 'Lou', 'credit_id...
1     [{'cast_id': 1, 'character': 'Mia Thermopolis'...
2     [{'cast_id': 5, 'character': 'Andrew Neimann',...
5     [{'cast_id': 6, 'character': 'Pinocchio (voice...
6     [{'cast_id': 23, 'character': 'Clyde', 'credit...
...                                                 ...
2994  [{'cast_id': 2, 'character': 'David Greene', '...
2995  [{'cast_id': 2, 'character': 'Rock Reilly', 'c...
2997  [{'cast_id': 10, 'character': 'Samantha Caine ...
2998  [{'cast_id': 8, 'character': 'Reuben Feffer', ...
2999  [{'cast_id': 2, 'character': 'Nathan Harper', ...

                                                   crew    revenue
0     [{'credit_id': '59ac067c92514107af02c8c8', 'de...   12314651
1     [{'credit_id': '52fe43fe9251416c7502563d', 'de...   95149435
2     [{'credit_id': '54d5356ec3a3683ba0000039', 'de...   13092000
5     [{'credit_id': '52fe46f49251416c9106558b', 'de...    3261638
6     [{'credit_id': '52fe4981c3a368484e12ee29', 'de...   85446075
...                                                 ...        ...
2994  [{'credit_id': '5637777ac3a3681b4d01f9f5', 'de...   14715067
2995  [{'credit_id': '52fe4494c3a368484e02ac7d', 'de...    1596687
2997  [{'credit_id': '52fe443a9251416c7502d579', 'de...   89456761
2998  [{'credit_id': '556f817b9251410866000a63', 'de...  171963386
2999  [{'credit_id': '5391990d0e0a260fb5001629', 'de...   82087155

[2575 rows x 23 columns]

### Question 2
Find all movies whose original language is Hindi (hi).

In [19]:
# Write your solution here
print(df[df['original_language']=='hi'])

        id                              belongs_to_collection    budget  \
3        4                                                NaN   1200000
213    214                                                NaN   6700000
371    372                                                NaN  13100000
401    402                                                NaN   3000000
419    420                                                NaN   3750000
481    482                                                NaN  10500000
585    586                                                NaN  10400000
627    628                                                NaN  16000000
671    672                                                NaN   6400000
695    696                                                NaN         1
771    772                                                NaN   9000000
840    841                                                NaN  10721568
848    849                                                NaN   6400000
970    971                                                NaN   4200000
1004  1005                                                NaN   1000000
1491  1492                                                NaN   5500000
1572  1573                                                NaN   9100000
1640  1641                                                NaN   4600000
1656  1657                                                NaN  18000000
1694  1695                                                NaN    521873
1719  1720                                                NaN   4437508
1729  1730                                                NaN   5200000
1732  1733  [{'id': 419784, 'name': 'Masti Collection', 'p...   5500000
1766  1767                                                NaN         0
1948  1949                                                NaN         0
1987  1988                                                NaN         0
1989  1990  [{'id': 20970, 'name': 'Sarkar Collection', 'p...   1900000
2239  2240  [{'id': 44976, 'name': 'Dhoom Series', 'poster...  19500000
2251  2252                                                NaN       130
2287  2288                                                NaN  18000000
2353  2354                                                NaN   8376800
2390  2391                                                NaN   7500000
2436  2437                                                NaN   4300000
2480  2481                                                NaN   6400000
2538  2539                                                NaN   6900000
2563  2564                                                NaN   7400000
2567  2568                                                NaN  11000000
2807  2808                                                NaN   5300000
2828  2829                                                NaN  19500000
2857  2858                                                NaN   5400000
2859  2860  [{'id': 286951, 'name': 'Singham Collection', ...   3062000
2959  2960                                                NaN   2300000

                                                 genres  \
3     [{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...
213                      [{'id': 28, 'name': 'Action'}]
371   [{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...
401   [{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...
419   [{'id': 35, 'name': 'Comedy'}, {'id': 10769, '...
481   [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...
585                       [{'id': 18, 'name': 'Drama'}]
627   [{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...
671   [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
695   [{'id': 10749, 'name': 'Romance'}, {'id': 53, ...
771   [{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...
840                       [{'id': 18, 'name': 'Drama'}]
848   [{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...
970   [{'id': 10749, 'name': 'Romance'}, {'id': 28, ...
1004  [{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...
1491  [{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...
1572  [{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...
1640  [{'id': 36, 'name': 'History'}, {'id': 28, 'na...
1656  [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...
1694  [{'id': 53, 'name': 'Thriller'}, {'id': 80, 'n...
1719  [{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...
1729  [{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...
1732  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
1766  [{'id': 10749, 'name': 'Romance'}, {'id': 18, ...
1948  [{'id': 35, 'name': 'Comedy'}, {'id': 80, 'nam...
1987  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
1989  [{'id': 80, 'name': 'Crime'}, {'id': 28, 'name...
2239  [{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...
2251  [{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...
2287  [{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...
2353  [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...
2390  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
2436  [{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...
2480  [{'id': 10749, 'name': 'Romance'}, {'id': 18, ...
2538  [{'id': 10749, 'name': 'Romance'}, {'id': 18, ...
2563  [{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...
2567  [{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...
2807  [{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...
2828  [{'id': 10752, 'name': 'War'}, {'id': 36, 'nam...
2857                   [{'id': 53, 'name': 'Thriller'}]
2859  [{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...
2959  [{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...

                                               homepage    imdb_id  \
3                            http://kahaanithefilm.com/  tt1821480
213                                                 NaN  tt2077833
371                     http://www.thankyouthefilm.com/  tt1720254
401                                                 NaN  tt0319736
419                       http://www.atithithefilm.com/  tt1578116
481                        http://www.cc2c-thefilm.com/  tt1091229
585                                                 NaN  tt5074352
627   http://www.yashrajfilms.com/Movies/MovieIndivi...  tt3495026
671     http://www.anjaanaanjaani.erosentertainment.com  tt1499201
695                                                 NaN  tt0374271
771                          http://kaminey.utvnet.com/  tt1274295
840              https://www.facebook.com/foxstarhindi/  tt5286444
848                                                 NaN  tt2359810
970                                                 NaN  tt3142232
1004                                                NaN  tt2350496
1491                                                NaN  tt3767372
1572                    http://www.rememberghajini.com/  tt1166100
1640                                                NaN  tt2356180
1656  http://www.chennaiexp2013.com/chennaiexpress.aspx  tt2112124
1694                                                NaN  tt5662932
1719  http://www.utvgroup.com/motion-pictures/coming...  tt2082197
1729                                                NaN  tt0164538
1732                                                NaN  tt2476154
1766                                                NaN  tt0290326
1948                                                NaN  tt0476805
1987                                                NaN  tt0347304
1989                                                NaN  tt0432047
2239                                                NaN  tt1833673
2251                                                NaN  tt1729637
2287                                                NaN  tt2979920
2353                        http://www.jodhaaakbar.com/  tt0449994
2390                http://www.khattameethathefilm.com/  tt1455811
2436                                                NaN  tt5946128
2480                                                NaN  tt2168910
2538                                                NaN  tt0151150
2563                                                NaN  tt0449999
2567                                                NaN  tt2424988
2807                                                NaN  tt0439662
2828                                                NaN  tt3735246
2857                                                NaN  tt2855648
2859                                                NaN  tt1948150
2959                                                NaN  tt1093370

     original_language              original_title  \
3                   hi                     Kahaani
213                 hi                 राउडी राठौर
371                 hi                   Thank You
401                 hi  The Legend of Bhagat Singh
419                 hi        Atithi Tum Kab Jaoge
481                 hi      Chandni Chowk To China
585                 hi                        दंगल
627                 hi                         Fan
671                 hi             Anjaana Anjaani
695                 hi                   Tere Naam
771                 hi                     Kaminey
840                 hi                       नीरजा
848                 hi                    रान्झाना
970                 hi                   Heropanti
1004                hi                       Dabba
1491                hi                        Piku
1572                hi                     Ghajini
1640                hi          Bhaag Milkha Bhaag
1656                hi             Chennai Express
1694                hi                रमन राघव २.०
1719                hi                      Barfi!
1729                hi                      दिल से
1732                hi                 Grand Masti
1766                hi                     Tum Bin
1948                hi               मालामाल वीकली
1987                hi                 कल हो ना हो
1989                hi                      Sarkar
2239                hi                       धूम ३
2251                hi                   Bodyguard
2287                hi               बॉम्बे वेलवेट
2353                hi                Jodhaa Akbar
2390                hi               Khatta Meetha
2436                hi                Dear Zindagi
2480                hi                    Cocktail
2538                hi                        Josh
2563                hi          कभी अलविदा ना कहना
2567                hi              Gabbar Is Back
2807                hi                       Fanaa
2828                hi             Bajirao Mastani
2857                hi                 Madras Cafe
2859                hi                     Singham
2959                hi                  Jab We Met

                                               overview  popularity  ...  \
3     Vidya Bagchi (Vidya Balan) arrives in Kolkata ...    3.174936  ...
213   Low-life thief Shiva and top-cop Vikram Rathor...    1.312833  ...
371   The film is about three husbands having affair...    1.417392  ...
401   The Legend of Bhagat Singh is a 2002 Indian hi...    0.904409  ...
419   Atithi Tum Kab Jaoge? is the story of Puneet a...    0.597058  ...
481   Based in Delhi's Chandni Chowk, orphaned Sidhu...    1.970481  ...
585   Dangal is an extraordinary true story based on...    8.792104  ...
627   The story of a fan whose world completely revo...    5.127876  ...
671   Akash (Ranbir Kapoor) and Kiara (Priyanka Chop...    1.822940  ...
695   Lower Caste Radhey Mohan is a no good slacker,...    1.280455  ...
771   Guddu and Charlie are identical twins born and...    2.089842  ...
840   Neerja is a portrayal on the life of the coura...    1.686250  ...
848   A small-town boy needs to break through the cl...    1.856101  ...
970   Rising from present India in the conflicting e...    2.031919  ...
1004  A mistaken delivery in Mumbai's famously effic...   10.766409  ...
1491  A road trip to Kolkata brings Piku, an archite...    2.942711  ...
1572  Sanjay a rich tycoon suffering from short term...    4.239080  ...
1640  The true story of the "Flying Sikh" world cham...    4.342418  ...
1656  Rahul embarks on a journey to a small town in ...    4.193560  ...
1694  Set in present day Mumbai the story follows th...    1.668794  ...
1719  He is cute. He's shrewd. The girls love him. T...    3.779077  ...
1729  The clash between love and ideology is portray...    1.891138  ...
1732  Amar, Prem and Meet are longtime friends who h...    1.250293  ...
1766  Shekhar, a businessman, accidentally kills his...    0.371679  ...
1948  Lilaram sells lottery tickets and one customer...    1.479018  ...
1987  Naina is a very serious girl with a very serio...    5.584308  ...
1989  The authority of a man, who runs a parallel go...    2.004745  ...
2239  To avenge his father's death, a circus enterta...    5.326716  ...
2251  Lovely Singh (Salman Khan) is the bodyguard of...    2.402032  ...
2287  An ordinary man, who goes against all odds to ...    1.377993  ...
2353  Jodhaa Akbar is a sixteenth century love story...   12.237488  ...
2390  Struggling road construction contractor, Sachi...    0.494047  ...
2436  An unconventional thinker (Shah Rukh Khan) hel...    3.699552  ...
2480  Gautam is an incorrigible flirt, who runs afte...    7.950488  ...
2538  Shah Rukh Khan and Sharad Kapoor are the leade...    4.031500  ...
2563  Dev and Maya are both married to different peo...    2.372520  ...
2567  A vigilante network taking out corrupt officia...    1.812728  ...
2807  Zooni Ali Beg (Kajol) is a blind Kashmiri girl...    3.003526  ...
2828  A historical account of the romance between th...    4.683689  ...
2857  An Indian Intelligence agent journeys into a w...    2.399890  ...
2859  A Bollywood classic directed by Rodit Shetty. ...    2.077410  ...
2959  Depressed after the passing of his father, Dha...    3.959411  ...

     release_date runtime                                   spoken_languages  \
3          3/9/12   122.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
213        6/1/12   143.0            [{'iso_639_1': 'hi', 'name': 'हिन्दी'}]
371        4/8/11   140.0            [{'iso_639_1': 'hi', 'name': 'हिन्दी'}]
401        6/7/02   155.0  [{'iso_639_1': 'pa', 'name': 'ਪੰਜਾਬੀ'}, {'iso_...
419       2/26/10   155.0            [{'iso_639_1': 'hi', 'name': 'हिन्दी'}]
481       1/16/09   149.0  [{'iso_639_1': 'de', 'name': 'Deutsch'}, {'iso...
585      12/23/16   161.0            [{'iso_639_1': 'hi', 'name': 'हिन्दी'}]
627       4/15/16   142.0            [{'iso_639_1': 'hi', 'name': 'हिन्दी'}]
671       9/24/10   151.0            [{'iso_639_1': 'hi', 'name': 'हिन्दी'}]
695       8/15/03   132.0            [{'iso_639_1': 'hi', 'name': 'हिन्दी'}]
771       8/14/09   135.0           [{'iso_639_1': 'de', 'name': 'Deutsch'}]
840       2/19/16   122.0            [{'iso_639_1': 'hi', 'name': 'हिन्दी'}]
848       6/21/13   140.0            [{'iso_639_1': 'hi', 'name': 'हिन्दी'}]
970       5/23/14   146.0            [{'iso_639_1': 'hi', 'name': 'हिन्दी'}]
1004      9/19/13   104.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
1491       5/8/15   123.0            [{'iso_639_1': 'hi', 'name': 'हिन्दी'}]
1572     12/25/08   183.0            [{'iso_639_1': 'hi', 'name': 'हिन्दी'}]
1640      7/12/13   186.0            [{'iso_639_1': 'hi', 'name': 'हिन्दी'}]
1656       8/9/13   141.0  [{'iso_639_1': 'hi', 'name': 'हिन्दी'}, {'iso_...
1694      6/24/16   127.0            [{'iso_639_1': 'hi', 'name': 'हिन्दी'}]
1719      9/14/12   155.0            [{'iso_639_1': 'hi', 'name': 'हिन्दी'}]
1729      8/22/98   163.0  [{'iso_639_1': 'hi', 'name': 'हिन्दी'}, {'iso_...
1732      9/13/13   140.0            [{'iso_639_1': 'hi', 'name': 'हिन्दी'}]
1766      7/13/01   158.0            [{'iso_639_1': 'hi', 'name': 'हिन्दी'}]
1948      3/10/06   138.0            [{'iso_639_1': 'hi', 'name': 'हिन्दी'}]
1987     11/27/03   186.0  [{'iso_639_1': 'de', 'name': 'Deutsch'}, {'iso...
1989       7/1/05   123.0            [{'iso_639_1': 'hi', 'name': 'हिन्दी'}]
2239     12/18/13   172.0            [{'iso_639_1': 'hi', 'name': 'हिन्दी'}]
2251      8/31/11   130.0            [{'iso_639_1': 'hi', 'name': 'हिन्दी'}]
2287      5/15/15   151.0            [{'iso_639_1': 'hi', 'name': 'हिन्दी'}]
2353      2/15/08   213.0  [{'iso_639_1': 'hi', 'name': 'हिन्दी'}, {'iso_...
2390      7/23/10   155.0            [{'iso_639_1': 'hi', 'name': 'हिन्दी'}]
2436     11/24/16   149.0            [{'iso_639_1': 'hi', 'name': 'हिन्दी'}]
2480      7/13/12   144.0            [{'iso_639_1': 'hi', 'name': 'हिन्दी'}]
2538       6/9/00   162.0  [{'iso_639_1': 'de', 'name': 'Deutsch'}, {'iso...
2563      8/11/06   193.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
2567       5/1/15   128.0            [{'iso_639_1': 'hi', 'name': 'हिन्दी'}]
2807      5/26/06   168.0  [{'iso_639_1': 'hi', 'name': 'हिन्दी'}, {'iso_...
2828     12/18/15   150.0  [{'iso_639_1': 'de', 'name': 'Deutsch'}, {'iso...
2857      8/23/13   130.0            [{'iso_639_1': 'hi', 'name': 'हिन्दी'}]
2859      7/22/11   143.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
2959     10/26/07   145.0  [{'iso_639_1': 'hi', 'name': 'हिन्दी'}, {'iso_...

        status                                            tagline  \
3     Released                                                NaN
213   Released                                                NaN
371   Released  Husbands will say sorry ... Wives will say tha...
401   Released                                                NaN
419   Released                                                NaN
481   Released                                                NaN
585   Released                                                NaN
627   Released  World's biggest superstar got the universe's b...
671   Released  All the greatest love stories...are between st...
695   Released                    Unfortunately a true love story
771   Released             Thif monfoon. Difcover your mean fide.
840   Released                              Fear Gave Her Courage
848   Released                                                NaN
970   Released                                                NaN
1004  Released                                                NaN
1491  Released                               Motion Se Hi Emotion
1572  Released                                                NaN
1640  Released                   Now you will see his Real Story.
1656  Released                             Ready... Steady... Po!
1694  Released                                                NaN
1719  Released                                                NaN
1729  Released                                                NaN
1732  Released                            The Masti Boys are Back
1766  Released                             Love Will Find the Way
1948  Released                                                NaN
1987  Released                                                NaN
1989  Released                                                NaN
2239  Released                                                NaN
2251  Released                                                NaN
2287  Released                                                NaN
2353  Released                                                NaN
2390  Released                                                NaN
2436  Released                                                NaN
2480  Released  Sometimes good friends may be too good to shar...
2538  Released                                                NaN
2563  Released            A Love.... That Broke All Relationships
2567  Released                                                NaN
2807  Released                               Destroyed in love...
2828  Released                                                NaN
2857  Released                                Intercept the truth
2859  Released                                                NaN
2959  Released                                                NaN

                                 title  \
3                              Kahaani

### Question 3
Display only the title and original_language columns for Hindi movies.

In [20]:
# Write your solution here
print(df[df['original_language']=='hi'][['title','original_language']])

                                 title original_language
3                              Kahaani                hi
213                      Rowdy Rathore                hi
371                          Thank You                hi
401         The Legend of Bhagat Singh                hi
419   Dear Guest, When Will You Leave?                hi
481             Chandni Chowk To China                hi
585                             Dangal                hi
627                                Fan                hi
671                    Anjaana Anjaani                hi
695                          Tere Naam                hi
771                            Kaminey                hi
840                             Neerja                hi
848                         Raanjhanaa                hi
970                          Heropanti                hi
1004                      The Lunchbox                hi
1491                              Piku                hi
1572                           Ghajini                hi
1640                Bhaag Milkha Bhaag                hi
1656                   Chennai Express                hi
1694                  Raman Raghav 2.0                hi
1719                             Barfi                hi
1729                          Dil Se..                hi
1732                       Grand Masti                hi
1766                           Tum Bin                hi
1948                   Malamaal Weekly                hi
1987                     Kal Ho Naa Ho                hi
1989                            Sarkar                hi
2239                           Dhoom 3                hi
2251                         Bodyguard                hi
2287                     Bombay Velvet                hi
2353                      Jodhaa Akbar                hi
2390                     Khatta Meetha                hi
2436                      Dear Zindagi                hi
2480                          Cocktail                hi
2538                              Josh                hi
2563            Kabhi Alvida Naa Kehna                hi
2567                    Gabbar Is Back                hi
2807                             Fanaa                hi
2828                   Bajirao Mastani                hi
2857                       Madras Cafe                hi
2859                           Singham                hi
2959                        Jab We Met                hi

### Question 4
Find movies having a budget greater than 100 million.

In [21]:
# Write your solution here
print(df[df['budget']>100000000])

        id                              belongs_to_collection     budget  \
14      15                                                NaN  102000000
34      35  [{'id': 90863, 'name': 'Rush Hour Collection',...  140000000
57      58  [{'id': 120794, 'name': 'Batman Collection', '...  125000000
60      61  [{'id': 645, 'name': 'James Bond Collection', ...  150000000
121    122  [{'id': 106768, 'name': 'Tarzan (Animation) Co...  150000000
...    ...                                                ...        ...
2866  2867  [{'id': 52984, 'name': 'National Treasure Coll...  130000000
2880  2881                                                NaN  150000000
2899  2900                                                NaN  127500000
2927  2928  [{'id': 645, 'name': 'James Bond Collection', ...  140000000
2938  2939  [{'id': 135416, 'name': 'Prometheus Collection...  130000000

                                                 genres  \
14    [{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...
34    [{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...
57    [{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...
60    [{'id': 12, 'name': 'Adventure'}, {'id': 28, '...
121   [{'id': 12, 'name': 'Adventure'}, {'id': 16, '...
...                                                 ...
2866  [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...
2880  [{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...
2899  [{'id': 16, 'name': 'Animation'}, {'id': 10751...
2927  [{'id': 12, 'name': 'Adventure'}, {'id': 28, '...
2938  [{'id': 878, 'name': 'Science Fiction'}, {'id'...

                                               homepage    imdb_id  \
14                                                  NaN  tt0181689
34                                                  NaN  tt0293564
57                                                  NaN  tt0118688
60    http://www.mgm.com/#/our-titles/233/Casino-Roy...  tt0381061
121   http://disneydvd.disney.go.com/tarzanr-special...  tt0120855
...                                                 ...        ...
2866  http://disney.go.com/disneypictures/nationaltr...  tt0465234
2880                                                NaN  tt2334879
2899                                                NaN  tt0130623
2927  http://www.mgm.com/view/movie/232/Die-Another-...  tt0246460
2938                  http://www.projectprometheus.com/  tt1446714

     original_language                      original_title  \
14                  en                     Minority Report
34                  en                         Rush Hour 3
57                  en                      Batman & Robin
60                  en                       Casino Royale
121                 en                              Tarzan
...                ...                                 ...
2866                en  National Treasure: Book of Secrets
2880                en                    White House Down
2899                en                            Dinosaur
2927                en                     Die Another Day
2938                en                          Prometheus

                                               overview  popularity  ...  \
14    John Anderton is a top 'Precrime' cop in the l...   20.666063  ...
34    After an attempted assassination on Ambassador...    9.718111  ...
57    Along with crime-fighting partner Robin and ne...   17.038824  ...
60    Le Chiffre, a banker to the world's terrorists...   23.065078  ...
121   Tarzan was a small orphan who was raised by an...   12.453452  ...
...                                                 ...         ...  ...
2866  Benjamin Franklin Gates and Dr. Abigail Chase ...   12.854373  ...
2880  Capitol Policeman John Cale has just been deni...    9.920223  ...
2899  An orphaned dinosaur raised by lemurs joins an...    9.998415  ...
2927  Bond takes on a North Korean leader who underg...   12.996474  ...
2938  A team of explorers discover a clue to the ori...   16.624854  ...

     release_date runtime                                   spoken_languages  \
14        6/20/02   145.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
34         8/8/07    91.0  [{'iso_639_1': 'la', 'name': 'Latin'}, {'iso_6...
57        6/20/97   125.0           [{'iso_639_1': 'en', 'name': 'English'}]
60       11/14/06   144.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
121       6/18/99    88.0           [{'iso_639_1': 'en', 'name': 'English'}]
...           ...     ...                                                ...
2866     12/13/07   124.0  [{'iso_639_1': 'la', 'name': 'Latin'}, {'iso_6...
2880      6/27/13   131.0           [{'iso_639_1': 'en', 'name': 'English'}]
2899      5/19/00    82.0           [{'iso_639_1': 'en', 'name': 'English'}]
2927     11/17/02   133.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
2938      5/30/12   124.0  [{'iso_639_1': 'gd', 'name': ''}, {'iso_639_1'...

        status                                            tagline  \
14    Released    The system is perfect until it comes after you.
34    Released                                    The Rush Is On!
57    Released             Strength. Courage. Honor. And loyalty.
60    Released  Everyone has a past. Every legend has a beginn...
121   Released       An immortal legend. As you've only imagined.
...        ...                                                ...
2866  Released   The Greatest Adventure History Has Ever Revealed
2880  Released                  It will start like any other day.
2899  Released            You have never seen anything like this.
2927  Released                            He’s never been cooler.
2938  Released  The Search for Our Beginning Could Lead to Our...

                                   title  \
14                       Minority Report
34                           Rush Hour 3
57                        Batman & Robin
60                         Casino Royale
121                               Tarzan
...                                  ...
2866  National Treasure: Book of Secrets
2880                    White House Down
2899                            Dinosaur
2927                     Die Another Day
2938                          Prometheus

                                               Keywords  \
14    [{'id': 476, 'name': 'self-fulfilling prophecy...
34                 [{'id': 1704, 'name': 'ambassador'}]
57    [{'id': 848, 'name': 'double life'}, {'id': 84...
60    [{'id': 131, 'name': 'italy'}, {'id': 383, 'na...
121   [{'id': 690, 'name': 'gorilla'}, {'id': 1009, ...
...                                                 ...
2866  [{'id': 90, 'name': 'paris'}, {'id': 212, 'nam...
2880  [{'id': 840, 'name': 'usa president'}, {'id': ...
2899  [{'id': 843, 'name': 'cataclysm'}, {'id': 1423...
2927  [{'id': 3290, 'name': 'laser'}, {'id': 156095,...
2938  [{'id': 803, 'name': 'android'}, {'id': 4565, ...

                                                   cast  \
14    [{'cast_id': 5, 'character': 'Chief John Ander...
34    [{'cast_id': 2, 'character': 'Det. James Carte...
57    [{'cast_id': 4, 'character': 'Bruce Wayne / Ba...
60    [{'cast_id': 1, 'character': 'James Bond', 'cr...
121   [{'cast_id': 9, 'character': 'Tarzan', 'credit...
...                                                 ...
2866  [{'cast_id': 1, 'character': 'Benjamin Frankli...
2880  [{'cast_id': 9, 'character': 'Cale', 'credit_i...
2899  [{'cast_id': 1, 'character': 'Aladar (voice)',...
2927  [{'cast_id': 20, 'character': 'James Bond', 'c...
2938  [{'cast_id': 5, 'character': 'Dr. Elizabeth Sh...

                                                   crew    revenue
14    [{'credit_id': '52fe4223c3a36847f8006f3d', 'de...  358372926
34    [{'credit_id': '52fe43fac3a36847f807b5bd', 'de...  258022233
57    [{'credit_id': '59b66a169251417cbc011ec4', 'de...  238207122
60    [{'credit_id': '53ac1fd7c3a3684bc8001908', 'de...  599045960
121   [{'credit_id': '5912c9a19251414e8005140a', 'de...  448000000
...                                                 ...        ...
2866  [{'credit_id': '52fe4460c3a36847f8092639', 'de...  457363168
2880  [{'credit_id': '52fe4baec3a36847f820f3b1', 'de...  205366737
2899  [{'credit_id': '52fe43899251416c75014337', 'de...  354248063
2927  [{'credit_id': '52fe45ff9251416c91045a7f', 'de...  431971116
2938  [{'credit_id': '52fe481dc3a368484e0e9db7', 'de...  403170142

[125 rows x 23 columns]

### Question 5
Find movies with revenue greater than 500 million.

In [22]:
# Write your solution here
df[df['revenue']>500000000]

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
46,47,"[{'id': 8354, 'name': 'Ice Age Collection', 'p...",80000000,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...",http://www.iceagemovies.com/films/ice-age-the-...,tt0438097,en,Ice Age: The Meltdown,"Diego, Manny and Sid return in this sequel to ...",16.646029,...,3/23/06,91.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Ice age is melting away.,Ice Age: The Meltdown,"[{'id': 2078, 'name': 'mammoth'}, {'id': 2079,...","[{'cast_id': 1, 'character': 'Manny (voice)', ...","[{'credit_id': '52fe4292c3a36847f80292c9', 'de...",660940780
60,61,"[{'id': 645, 'name': 'James Bond Collection', ...",150000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",http://www.mgm.com/#/our-titles/233/Casino-Roy...,tt0381061,en,Casino Royale,"Le Chiffre, a banker to the world's terrorists...",23.065078,...,11/14/06,144.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Everyone has a past. Every legend has a beginn...,Casino Royale,"[{'id': 131, 'name': 'italy'}, {'id': 383, 'na...","[{'cast_id': 1, 'character': 'James Bond', 'cr...","[{'credit_id': '53ac1fd7c3a3684bc8001908', 'de...",599045960
114,115,"[{'id': 119, 'name': 'The Lord of the Rings Co...",93000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",http://www.lordoftherings.net/,tt0120737,en,The Lord of the Rings: The Fellowship of the Ring,"Young hobbit Frodo Baggins, after inheriting a...",32.070725,...,12/18/01,178.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,One ring to rule them all,The Lord of the Rings: The Fellowship of the Ring,"[{'id': 603, 'name': 'elves'}, {'id': 604, 'na...","[{'cast_id': 28, 'character': 'Frodo Baggins',...","[{'credit_id': '52fe421ac3a36847f80043ef', 'de...",871368364
188,189,NaN,180000000,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...",http://disney.go.com/disneypictures/wall-e/,tt0910970,en,WALL·E,WALL·E is the last robot left on an Earth that...,16.088366,...,6/22/08,98.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,An adventure beyond the ordinar-E.,WALL·E,"[{'id': 9799, 'name': 'romantic comedy'}]","[{'cast_id': 12, 'character': 'WALL¬∑E / M-O (...","[{'credit_id': '52fe43a29251416c75018101', 'de...",521311860
203,204,NaN,75000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://www.simpsonsmovie.com/,tt0462538,en,The Simpsons Movie,After Homer accidentally pollutes the town's w...,14.302911,...,7/25/07,87.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,See our family. And feel better about yours.,The Simpsons Movie,"[{'id': 494, 'name': 'father son relationship'...","[{'cast_id': 2, 'character': ""Homer / Itchy / ...","[{'credit_id': '52fe4211c3a36847f8001521', 'de...",527068851
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2647,2648,"[{'id': 87359, 'name': 'Mission: Impossible Co...",145000000,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",http://www.missionimpossible.com/,tt1229238,en,Mission: Impossible - Ghost Protocol,In the 4th installment of the Mission Impossib...,14.258430,...,12/7/11,133.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,No Plan. No Backup. No Choice.,Mission: Impossible - Ghost Protocol,"[{'id': 1721, 'name': 'fight'}, {'id': 9663, '...","[{'cast_id': 5, 'character': 'Ethan Hunt', 'cr...","[{'credit_id': '53563fb00e0a262861002dd0', 'de...",694713380
2737,2738,"[{'id': 645, 'name': 'James Bond Collection', ...",245000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://www.sonypictures.com/movies/spectre/,tt2379713,en,Spectre,A cryptic message from Bond‚Äôs past sends him...,24.926577,...,10/26/15,148.0,"[{'iso_639_1': 'fr', 'name': 'Français'}, {'is...",Released,A Plan No One Escapes,Spectre,"[{'id': 470, 'name': 'spy'}, {'id': 818, 'name...","[{'cast_id': 1, 'character': 'James Bond', 'cr...","[{'credit_id': '5751eed59251416b60000637', 'de...",880674609
2739,2740,"[{'id': 468222, 'name': 'The Incredibles Colle...",92000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://disney.go.com/disneyvideos/animatedfilm...,tt0317705,en,The Incredibles,Bob Parr has given up his superhero days to lo...,22.220214,...,11/5/04,115.0,"[{'iso_639_1': 'fr', 'name': 'Français'}, {'is...",Released,"No gut, no glory",The Incredibles,"[{'id': 1308, 'name': 'secret identity'}, {'id...","[{'cast_id': 1, 'character': 'Bob Parr / Mr. I...","[{'credit_id': '52fe4531c3a36847f80c159d', 'de...",631442092
2770,2771,"[{'id': 86311, 'name': 'The Avengers Collectio...",280000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://marvel.com/movies/movie/193/avengers_ag...,tt2395427,en,Avengers: Age of Ultron,When Tony Stark tries to jumpstart a dormant p...,37.379420,...,4/22/15,141.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A New Age Has Come.,Avengers: Age of Ultron,"[{'id': 8828, 'name': 'marvel comic'}, {'id': ...","[{'cast_id': 76, 'character': 'Tony Stark / Ir...","[{'credit_id': '55d5f7d4c3a3683e7e0016eb', 'de...",1405403694
2802,2803,"[{'id': 1241, 'name': 'Harry Potter Collection...",100000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,tt0295297,en,Harry Potter and the Chamber of Secrets,"Ignoring threats to his life, Harry returns to...",29.741452,...,11/13/02,161.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Hogwarts is back in session.,Harry Potter and the Chamber of Secrets,"[{'id': 391, 'name': 'flying car'}, {'id': 616...","[{'cast_id': 23, 'character': 'Harry Potter', ...","[{'credit_id': '52fe4267c3a36847f801bf67', 'de...",876688482

### Question 6
Find movies whose runtime is greater than 150 minutes.

In [23]:
# Write your solution here
print(df[df['runtime']>150])

        id belongs_to_collection    budget  \
47      48                   NaN  44000000
51      52                   NaN  12000000
76      77                   NaN    500000
97      98                   NaN         0
107    108                   NaN  72000000
...    ...                   ...       ...
2860  2861                   NaN  22000000
2877  2878                   NaN  18000000
2932  2933                   NaN  12000000
2944  2945                   NaN  31500000
2965  2966                   NaN  61000000

                                                 genres  \
47    [{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...
51    [{'id': 12, 'name': 'Adventure'}, {'id': 35, '...
76    [{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...
97    [{'id': 14, 'name': 'Fantasy'}, {'id': 18, 'na...
107   [{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...
...                                                 ...
2860  [{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...
2877  [{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...
2932  [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...
2944  [{'id': 18, 'name': 'Drama'}, {'id': 10752, 'n...
2965  [{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...

                              homepage    imdb_id original_language  \
47         http://thehatefuleight.com/  tt3460252                en
51                                 NaN  tt0059243                en
76                                 NaN  tt0242572                ta
97                                 NaN  tt1772980                ru
107                                NaN  tt0112573                en
...                                ...        ...               ...
2860                               NaN  tt0083987                en
2877                               NaN  tt0086879                en
2932                               NaN  tt0060934                en
2944      http://www.apocalypsenow.com  tt0078788                en
2965  http://www.lesmiserablesfilm.com  tt1707386                en

                 original_title  \
47            The Hateful Eight
51               The Great Race
76    Kandukondain Kandukondain
97                       Mishen
107                  Braveheart
...                         ...
2860                     Gandhi
2877                    Amadeus
2932           The Sand Pebbles
2944             Apocalypse Now
2965             Les Misérables

                                               overview  popularity  ...  \
47    Bounty hunters seek shelter from a raging bliz...   20.328822  ...
51    Professional daredevil and white-suited hero, ...    4.473327  ...
76    Two young women with differing views on love f...    0.660663  ...
97    In the year 2020, a group of wealthy Moscovite...    1.042112  ...
107   Enraged at the slaughter of Murron, his new br...   20.755149  ...
...                                                 ...         ...  ...
2860  In the early years of the 20th century, Mohand...   12.383755  ...
2877  The incredible story of genius musician Wolfga...   12.677592  ...
2932  Engineer Jake Holman arrives aboard the gunboa...   11.354247  ...
2944  At the height of the Vietnam war, Captain Benj...   13.596300  ...
2965  An adaptation of the successful stage musical ...   13.524080  ...

     release_date runtime                                   spoken_languages  \
47       12/25/15   167.0  [{'iso_639_1': 'es', 'name': 'Español'}, {'iso...
51         7/1/65   160.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
76         5/5/00   157.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
97        6/26/11   158.0  [{'iso_639_1': 'de', 'name': 'Deutsch'}, {'iso...
107       5/24/95   177.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
...           ...     ...                                                ...
2860     11/30/82   191.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
2877     10/26/84   160.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
2932     12/20/66   182.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
2944      8/15/79   153.0  [{'iso_639_1': 'km', 'name': ''}, {'iso_639_1'...
2965     12/18/12   157.0           [{'iso_639_1': 'en', 'name': 'English'}]

        status                                            tagline  \
47    Released   No one comes up here without a damn good reason.
51    Released  The movie with 20,000-mile or one-million-laug...
76    Released                                                NaN
97    Released                                                NaN
107   Released         Every man dies. Not every man truly lives.
...        ...                                                ...
2860  Released             His triumph changed the world forever.
2877  Released                 ...Everything you've heard is true
2932  Released  This is the heroic story of the men on the U.S...
2944  Released                                 This is the end...
2965  Released                          Fight. Dream. Hope. Love.

                          title  \
47            The Hateful Eight
51               The Great Race
76    Kandukondain Kandukondain
97                       Target
107                  Braveheart
...                         ...
2860                     Gandhi
2877                    Amadeus
2932           The Sand Pebbles
2944             Apocalypse Now
2965             Les Misérables

                                               Keywords  \
47    [{'id': 801, 'name': 'bounty hunter'}, {'id': ...
51    [{'id': 9253, 'name': 'slapstick'}, {'id': 159...
76                                                  NaN
97                                                  NaN
107   [{'id': 30, 'name': 'individual'}, {'id': 388,...
...                                                 ...
2860  [{'id': 789, 'name': 'muslim'}, {'id': 958, 'n...
2877  [{'id': 131, 'name': 'italy'}, {'id': 1233, 'n...
2932  [{'id': 440, 'name': 'missionary'}, {'id': 478...
2944  [{'id': 1008, 'name': 'guerrilla'}, {'id': 126...
2965  [{'id': 254, 'name': 'france'}, {'id': 642, 'n...

                                                   cast  \
47    [{'cast_id': 22, 'character': 'Major Marquis W...
51    [{'cast_id': 1, 'character': 'Prof. Fate', 'cr...
76    [{'cast_id': 1, 'character': 'Manohar', 'credi...
97    [{'cast_id': 1001, 'character': 'Victor', 'cre...
107   [{'cast_id': 5, 'character': 'William Wallace'...
...                                                 ...
2860  [{'cast_id': 7, 'character': 'Mahatma Gandhi',...
2877  [{'cast_id': 4, 'character': 'Antonio Salieri'...
2932  [{'cast_id': 1, 'character': 'Jake Holman', 'c...
2944  [{'cast_id': 29, 'character': 'Captain Benjami...
2965                                                NaN

                                                   crew    revenue
47    [{'credit_id': '538aa95ec3a368714e0005b3', 'de...  155760117
51    [{'credit_id': '52fe445e9251416c75032581', 'de...   25333333
76    [{'credit_id': '52fe47c7c3a368484e0d8f41', 'de...     500000
97    [{'credit_id': '58cdbad4c3a36850e9011085', 'de...      73000
107   [{'credit_id': '52fe4225c3a36847f80079c1', 'de...  210000000
...                                                 ...        ...
2860  [{'credit_id': '574dc2c3925141120e0000cb', 'de...   77737889
2877  [{'credit_id': '57d19657c3a3684b9d008667', 'de...   51973029
2932  [{'credit_id': '52fe442ec3a36847f8087029', 'de...   20000000
2944  [{'credit_id': '52fe4210c3a36847f80012c7', 'de...   89460381
2965                                                NaN  441809770

[127 rows x 23 columns]

### Question 7
Find movies with popularity greater than the average popularity.

In [24]:
# Write your solution here
print(df[df['popularity']>df['popularity'].mean()])

        id                              belongs_to_collection    budget  \
2        3                                                NaN   3300000
10      11  [{'id': 1575, 'name': 'Rocky Collection', 'pos...   1000000
11      12  [{'id': 48190, 'name': 'Revenge of the Nerds C...         0
12      13                                                NaN  15000000
13      14  [{'id': 91698, 'name': 'Chili Palmer Collectio...  53000000
...    ...                                                ...       ...
2993  2994                                                NaN  60000000
2995  2996                                                NaN         0
2997  2998                                                NaN  65000000
2998  2999                                                NaN  42000000
2999  3000                                                NaN  35000000

                                                 genres  \
2                         [{'id': 18, 'name': 'Drama'}]
10                        [{'id': 18, 'name': 'Drama'}]
11                       [{'id': 35, 'name': 'Comedy'}]
12                        [{'id': 18, 'name': 'Drama'}]
13    [{'id': 35, 'name': 'Comedy'}, {'id': 80, 'nam...
...                                                 ...
2993  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
2995  [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...
2997  [{'id': 80, 'name': 'Crime'}, {'id': 28, 'name...
2998  [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...
2999  [{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...

                                  homepage    imdb_id original_language  \
2        http://sonyclassics.com/whiplash/  tt2582802                en
10                                     NaN  tt0075148                en
11                                     NaN  tt0093857                en
12           http://www.dreamworks.com/ab/  tt0169547                en
13                                     NaN  tt0377471                en
...                                    ...        ...               ...
2993  http://www.theterminal-themovie.com/  tt0362227                en
2995                                   NaN  tt0109403                en
2997                                   NaN  tt0116908                en
2998        http://www.alongcamepolly.com/  tt0343135                en
2999      http://www.abductionthefilm.com/  tt1600195                en

                                  original_title  \
2                                       Whiplash
10                                         Rocky
11    Revenge of the Nerds II: Nerds in Paradise
12                               American Beauty
13                                       Be Cool
...                                          ...
2993                                The Terminal
2995                                     Chasers
2997                     The Long Kiss Goodnight
2998                            Along Came Polly
2999                                   Abduction

                                               overview  popularity  ...  \
2     Under the direction of a ruthless instructor, ...   64.299990  ...
10    When world heavyweight boxing champion, Apollo...   14.774066  ...
11    The members of the Lambda Lambda Lambda frater...   10.543750  ...
12    Lester Burnham, a depressed suburban father in...   20.726578  ...
13    Disenchanted with the movie industry, Chili Pa...   13.314233  ...
...                                                 ...         ...  ...
2993  Viktor Navorski is a man without a country; hi...   14.092373  ...
2995  Military men Rock Reilly and Eddie Devane are ...    9.853270  ...
2997  Samantha Caine, suburban homemaker, is the ide...   14.482345  ...
2998  Reuben Feffer is a guy who's spent his entire ...   15.725542  ...
2999  A young man sets out to uncover the truth abou...   10.512109  ...

     release_date runtime                                   spoken_languages  \
2        10/10/14   105.0           [{'iso_639_1': 'en', 'name': 'English'}]
10       11/21/76   119.0           [{'iso_639_1': 'en', 'name': 'English'}]
11        7/10/87    98.0           [{'iso_639_1': 'en', 'name': 'English'}]
12        9/15/99   122.0           [{'iso_639_1': 'en', 'name': 'English'}]
13         3/4/05   118.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
...           ...     ...                                                ...
2993      6/17/04   128.0  [{'iso_639_1': 'bg', 'name': 'български език'}...
2995      4/22/94   102.0           [{'iso_639_1': 'en', 'name': 'English'}]
2997     10/11/96   120.0           [{'iso_639_1': 'en', 'name': 'English'}]
2998      1/16/04    90.0           [{'iso_639_1': 'en', 'name': 'English'}]
2999      9/22/11   106.0           [{'iso_639_1': 'en', 'name': 'English'}]

        status                                            tagline  \
2     Released    The road to greatness can take you to the edge.
10    Released          His whole life was a million-to-one shot.
11    Released                                      They're Back!
12    Released                                       Look closer.
13    Released           Everyone is looking for the next big hit
...        ...                                                ...
2993  Released                                   Life is waiting.
2995  Released  It was supposed to be a routine prisoner trans...
2997  Released               What's forgotten is not always gone.
2998  Released  For the most cautious man on Earth, life is ab...
2999  Released          They stole his life. He's taking it back.

                                           title  \
2                                       Whiplash
10                                         Rocky
11    Revenge of the Nerds II: Nerds in Paradise
12                               American Beauty
13                                       Be Cool
...                                          ...
2993                                The Terminal
2995                                     Chasers
2997                     The Long Kiss Goodnight
2998                            Along Came Polly
2999                                   Abduction

                                               Keywords  \
2     [{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...
10    [{'id': 240, 'name': 'underdog'}, {'id': 276, ...
11    [{'id': 5801, 'name': 'nerd'}, {'id': 6876, 'n...
12    [{'id': 255, 'name': 'male nudity'}, {'id': 29...
13    [{'id': 3605, 'name': 'baseball bat'}, {'id': ...
...                                                 ...
2993  [{'id': 242, 'name': 'new york'}, {'id': 822, ...
2995  [{'id': 378, 'name': 'prison'}, {'id': 572, 'n...
2997  [{'id': 441, 'name': 'assassination'}, {'id': ...
2998  [{'id': 966, 'name': 'beach'}, {'id': 2676, 'n...
2999  [{'id': 591, 'name': 'cia'}, {'id': 822, 'name...

                                                   cast  \
2     [{'cast_id': 5, 'character': 'Andrew Neimann',...
10    [{'cast_id': 16, 'character': 'Rocky Balboa', ...
11    [{'cast_id': 2, 'character': 'Lewis Skolnick',...
12    [{'cast_id': 6, 'character': 'Lester Burnham',...
13    [{'cast_id': 4, 'character': 'Chili Palmer', '...
...                                                 ...
2993  [{'cast_id': 4, 'character': 'Viktor Navorski'...
2995  [{'cast_id': 2, 'character': 'Rock Reilly', 'c...
2997  [{'cast_id': 10, 'character': 'Samantha Caine ...
2998  [{'cast_id': 8, 'character': 'Reuben Feffer', ...
2999  [{'cast_id': 2, 'character': 'Nathan Harper', ...

                                                   crew    revenue
2     [{'credit_id': '54d5356ec3a3683ba0000039', 'de...   13092000
10    [{'credit_id': '579948e9c3a36874e9007b0b', 'de...  117235147
11    [{'credit_id': '52fe46f49251416c750891e9', 'de...   22642033
12    [{'credit_id': '52fe420ec3a36847f80007c5', 'de...  356296601
13    [{'credit_id': '52fe43cbc3a36847f807039f', 'de...   95226116
...                                                 ...        ...
2993  [{'credit_id': '52fe4259c3a36847f8017699', 'de...  219417255
2995  [{'credit_id': '52fe4494c3a368484e02ac7d', 'de...    1596687
2997  [{'credit_id': '52fe443a9251416c7502d579', 'de...   89456761
2998  [{'credit_id': '556f817b9251410866000a63', 'de...  171963386
2999  [{'credit_id': '5391990d0e0a260fb5001629', 'de...   82087155

[1211 rows x 23 columns]

### Question 8
Find all movies having a vote_average greater than 8.

In [25]:
# Write your solution here

### Question 1
Create a new column called half_runtime.

In [26]:
# Write your solution here
df['half_runtime']=df['runtime']/2
df

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue,half_runtime
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651,46.5
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435,56.5
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000,52.5
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,122.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000,61.0
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,118.0,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970,59.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,2996,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",NaN,tt0109403,en,Chasers,Military men Rock Reilly and Eddie Devane are ...,9.853270,...,102.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It was supposed to be a routine prisoner trans...,Chasers,"[{'id': 378, 'name': 'prison'}, {'id': 572, 'n...","[{'cast_id': 2, 'character': 'Rock Reilly', 'c...","[{'credit_id': '52fe4494c3a368484e02ac7d', 'de...",1596687,51.0
2996,2997,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...",NaN,tt2364975,sv,Vi är bäst!,Three girls in 1980s Stockholm decide to form ...,3.727996,...,102.0,"[{'iso_639_1': 'sv', 'name': 'svenska'}]",Released,NaN,We Are the Best!,"[{'id': 1192, 'name': 'sweden'}, {'id': 4470, ...","[{'cast_id': 5, 'character': 'Bobo', 'credit_i...","[{'credit_id': '5716b72ac3a3686678012c84', 'de...",180590,51.0
2997,2998,NaN,65000000,"[{'id': 80, 'name': 'Crime'}, {'id': 28, 'name...",NaN,tt0116908,en,The Long Kiss Goodnight,"Samantha Caine, suburban homemaker, is the ide...",14.482345,...,120.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,What's forgotten is not always gone.,The Long Kiss Goodnight,"[{'id': 441, 'name': 'assassination'}, {'id': ...","[{'cast_id': 10, 'character': 'Samantha Caine ...","[{'credit_id': '52fe443a9251416c7502d579', 'de...",89456761,60.0
2998,2999,NaN,42000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",http://www.alongcamepolly.com/,tt0343135,en,Along Came Polly,Reuben Feffer is a guy who's spent his entire ...,15.725542,...,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"For the most cautious man on Earth, life is ab...",Along Came Polly,"[{'id': 966, 'name': 'beach'}, {'id': 2676, 'n...","[{'cast_id': 8, 'character': 'Reuben Feffer', ...","[{'credit_id': '556f817b9251410866000a63', 'de...",171963386,45.0
2999,3000,NaN,35000000,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",http://www.abductionthefilm.com/,tt1600195,en,Abduction,A young man sets out to uncover the truth abou...,10.512109,...,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,They stole his life. He's taking it back.,Abduction,"[{'id': 591, 'name': 'cia'}, {'id': 822, 'name...","[{'cast_id': 2, 'character': 'Nathan Harper', ...","[{'credit_id': '5391990d0e0a260fb5001629', 'de...",82087155,53.0

### Question 2
Create a new column called double_runtime.

In [27]:
# Write your solution here
df['double_runtime']=df['runtime']*2
df

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue,half_runtime,double_runtime
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651,46.5,186.0
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435,56.5,226.0
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000,52.5,210.0
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000,61.0,244.0
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970,59.0,236.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,2996,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",NaN,tt0109403,en,Chasers,Military men Rock Reilly and Eddie Devane are ...,9.853270,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It was supposed to be a routine prisoner trans...,Chasers,"[{'id': 378, 'name': 'prison'}, {'id': 572, 'n...","[{'cast_id': 2, 'character': 'Rock Reilly', 'c...","[{'credit_id': '52fe4494c3a368484e02ac7d', 'de...",1596687,51.0,204.0
2996,2997,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...",NaN,tt2364975,sv,Vi är bäst!,Three girls in 1980s Stockholm decide to form ...,3.727996,...,"[{'iso_639_1': 'sv', 'name': 'svenska'}]",Released,NaN,We Are the Best!,"[{'id': 1192, 'name': 'sweden'}, {'id': 4470, ...","[{'cast_id': 5, 'character': 'Bobo', 'credit_i...","[{'credit_id': '5716b72ac3a3686678012c84', 'de...",180590,51.0,204.0
2997,2998,NaN,65000000,"[{'id': 80, 'name': 'Crime'}, {'id': 28, 'name...",NaN,tt0116908,en,The Long Kiss Goodnight,"Samantha Caine, suburban homemaker, is the ide...",14.482345,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,What's forgotten is not always gone.,The Long Kiss Goodnight,"[{'id': 441, 'name': 'assassination'}, {'id': ...","[{'cast_id': 10, 'character': 'Samantha Caine ...","[{'credit_id': '52fe443a9251416c7502d579', 'de...",89456761,60.0,240.0
2998,2999,NaN,42000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",http://www.alongcamepolly.com/,tt0343135,en,Along Came Polly,Reuben Feffer is a guy who's spent his entire ...,15.725542,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"For the most cautious man on Earth, life is ab...",Along Came Polly,"[{'id': 966, 'name': 'beach'}, {'id': 2676, 'n...","[{'cast_id': 8, 'character': 'Reuben Feffer', ...","[{'credit_id': '556f817b9251410866000a63', 'de...",171963386,45.0,180.0
2999,3000,NaN,35000000,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",http://www.abductionthefilm.com/,tt1600195,en,Abduction,A young man sets out to uncover the truth abou...,10.512109,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,They stole his life. He's taking it back.,Abduction,"[{'id': 591, 'name': 'cia'}, {'id': 822, 'name...","[{'cast_id': 2, 'character': 'Nathan Harper', ...","[{'credit_id': '5391990d0e0a260fb5001629', 'de...",82087155,53.0,212.0

### Question 3
Create a new column called profit = revenue - budget.

In [28]:
# Write your solution here
df['profit']=df['revenue']-df['budget']
df

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,status,tagline,title,Keywords,cast,crew,revenue,half_runtime,double_runtime,profit
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651,46.5,186.0,-1685349
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435,56.5,226.0,55149435
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000,52.5,210.0,9792000
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000,61.0,244.0,14800000
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970,59.0,236.0,3923970
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,2996,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",NaN,tt0109403,en,Chasers,Military men Rock Reilly and Eddie Devane are ...,9.853270,...,Released,It was supposed to be a routine prisoner trans...,Chasers,"[{'id': 378, 'name': 'prison'}, {'id': 572, 'n...","[{'cast_id': 2, 'character': 'Rock Reilly', 'c...","[{'credit_id': '52fe4494c3a368484e02ac7d', 'de...",1596687,51.0,204.0,1596687
2996,2997,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...",NaN,tt2364975,sv,Vi är bäst!,Three girls in 1980s Stockholm decide to form ...,3.727996,...,Released,NaN,We Are the Best!,"[{'id': 1192, 'name': 'sweden'}, {'id': 4470, ...","[{'cast_id': 5, 'character': 'Bobo', 'credit_i...","[{'credit_id': '5716b72ac3a3686678012c84', 'de...",180590,51.0,204.0,180590
2997,2998,NaN,65000000,"[{'id': 80, 'name': 'Crime'}, {'id': 28, 'name...",NaN,tt0116908,en,The Long Kiss Goodnight,"Samantha Caine, suburban homemaker, is the ide...",14.482345,...,Released,What's forgotten is not always gone.,The Long Kiss Goodnight,"[{'id': 441, 'name': 'assassination'}, {'id': ...","[{'cast_id': 10, 'character': 'Samantha Caine ...","[{'credit_id': '52fe443a9251416c7502d579', 'de...",89456761,60.0,240.0,24456761
2998,2999,NaN,42000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",http://www.alongcamepolly.com/,tt0343135,en,Along Came Polly,Reuben Feffer is a guy who's spent his entire ...,15.725542,...,Released,"For the most cautious man on Earth, life is ab...",Along Came Polly,"[{'id': 966, 'name': 'beach'}, {'id': 2676, 'n...","[{'cast_id': 8, 'character': 'Reuben Feffer', ...","[{'credit_id': '556f817b9251410866000a63', 'de...",171963386,45.0,180.0,129963386
2999,3000,NaN,35000000,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",http://www.abductionthefilm.com/,tt1600195,en,Abduction,A young man sets out to uncover the truth abou...,10.512109,...,Released,They stole his life. He's taking it back.,Abduction,"[{'id': 591, 'name': 'cia'}, {'id': 822, 'name...","[{'cast_id': 2, 'character': 'Nathan Harper', ...","[{'credit_id': '5391990d0e0a260fb5001629', 'de...",82087155,53.0,212.0,47087155

### Question 4
Create a new column called profit_percentage.

In [29]:
# Write your solution here
df["profit_percentage"]=(df['profit']/df['budget'])*100
df

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,tagline,title,Keywords,cast,crew,revenue,half_runtime,double_runtime,profit,profit_percentage
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651,46.5,186.0,-1685349,-12.038207
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435,56.5,226.0,55149435,137.873588
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000,52.5,210.0,9792000,296.727273
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000,61.0,244.0,14800000,1233.333333
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970,59.0,236.0,3923970,inf
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,2996,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",NaN,tt0109403,en,Chasers,Military men Rock Reilly and Eddie Devane are ...,9.853270,...,It was supposed to be a routine prisoner trans...,Chasers,"[{'id': 378, 'name': 'prison'}, {'id': 572, 'n...","[{'cast_id': 2, 'character': 'Rock Reilly', 'c...","[{'credit_id': '52fe4494c3a368484e02ac7d', 'de...",1596687,51.0,204.0,1596687,inf
2996,2997,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...",NaN,tt2364975,sv,Vi är bäst!,Three girls in 1980s Stockholm decide to form ...,3.727996,...,NaN,We Are the Best!,"[{'id': 1192, 'name': 'sweden'}, {'id': 4470, ...","[{'cast_id': 5, 'character': 'Bobo', 'credit_i...","[{'credit_id': '5716b72ac3a3686678012c84', 'de...",180590,51.0,204.0,180590,inf
2997,2998,NaN,65000000,"[{'id': 80, 'name': 'Crime'}, {'id': 28, 'name...",NaN,tt0116908,en,The Long Kiss Goodnight,"Samantha Caine, suburban homemaker, is the ide...",14.482345,...,What's forgotten is not always gone.,The Long Kiss Goodnight,"[{'id': 441, 'name': 'assassination'}, {'id': ...","[{'cast_id': 10, 'character': 'Samantha Caine ...","[{'credit_id': '52fe443a9251416c7502d579', 'de...",89456761,60.0,240.0,24456761,37.625786
2998,2999,NaN,42000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",http://www.alongcamepolly.com/,tt0343135,en,Along Came Polly,Reuben Feffer is a guy who's spent his entire ...,15.725542,...,"For the most cautious man on Earth, life is ab...",Along Came Polly,"[{'id': 966, 'name': 'beach'}, {'id': 2676, 'n...","[{'cast_id': 8, 'character': 'Reuben Feffer', ...","[{'credit_id': '556f817b9251410866000a63', 'de...",171963386,45.0,180.0,129963386,309.436633
2999,3000,NaN,35000000,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",http://www.abductionthefilm.com/,tt1600195,en,Abduction,A young man sets out to uncover the truth abou...,10.512109,...,They stole his life. He's taking it back.,Abduction,"[{'id': 591, 'name': 'cia'}, {'id': 822, 'name...","[{'cast_id': 2, 'character': 'Nathan Harper', ...","[{'credit_id': '5391990d0e0a260fb5001629', 'de...",82087155,53.0,212.0,47087155,134.534729

### Question 5
Create a column named budget_in_crores.

In [30]:
# Write your solution here
df['budget_in_crores']=df['budget']/10000000

### Question 6
Create a column named runtime_hours.

In [31]:
# Write your solution here
df['runtime_hours']=df['runtime']/60
df

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,Keywords,cast,crew,revenue,half_runtime,double_runtime,profit,profit_percentage,budget_in_crores,runtime_hours
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651,46.5,186.0,-1685349,-12.038207,1.40,1.550000
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435,56.5,226.0,55149435,137.873588,4.00,1.883333
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000,52.5,210.0,9792000,296.727273,0.33,1.750000
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000,61.0,244.0,14800000,1233.333333,0.12,2.033333
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970,59.0,236.0,3923970,inf,0.00,1.966667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,2996,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",NaN,tt0109403,en,Chasers,Military men Rock Reilly and Eddie Devane are ...,9.853270,...,"[{'id': 378, 'name': 'prison'}, {'id': 572, 'n...","[{'cast_id': 2, 'character': 'Rock Reilly', 'c...","[{'credit_id': '52fe4494c3a368484e02ac7d', 'de...",1596687,51.0,204.0,1596687,inf,0.00,1.700000
2996,2997,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...",NaN,tt2364975,sv,Vi är bäst!,Three girls in 1980s Stockholm decide to form ...,3.727996,...,"[{'id': 1192, 'name': 'sweden'}, {'id': 4470, ...","[{'cast_id': 5, 'character': 'Bobo', 'credit_i...","[{'credit_id': '5716b72ac3a3686678012c84', 'de...",180590,51.0,204.0,180590,inf,0.00,1.700000
2997,2998,NaN,65000000,"[{'id': 80, 'name': 'Crime'}, {'id': 28, 'name...",NaN,tt0116908,en,The Long Kiss Goodnight,"Samantha Caine, suburban homemaker, is the ide...",14.482345,...,"[{'id': 441, 'name': 'assassination'}, {'id': ...","[{'cast_id': 10, 'character': 'Samantha Caine ...","[{'credit_id': '52fe443a9251416c7502d579', 'de...",89456761,60.0,240.0,24456761,37.625786,6.50,2.000000
2998,2999,NaN,42000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",http://www.alongcamepolly.com/,tt0343135,en,Along Came Polly,Reuben Feffer is a guy who's spent his entire ...,15.725542,...,"[{'id': 966, 'name': 'beach'}, {'id': 2676, 'n...","[{'cast_id': 8, 'character': 'Reuben Feffer', ...","[{'credit_id': '556f817b9251410866000a63', 'de...",171963386,45.0,180.0,129963386,309.436633,4.20,1.500000
2999,3000,NaN,35000000,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",http://www.abductionthefilm.com/,tt1600195,en,Abduction,A young man sets out to uncover the truth abou...,10.512109,...,"[{'id': 591, 'name': 'cia'}, {'id': 822, 'name...","[{'cast_id': 2, 'character': 'Nathan Harper', ...","[{'credit_id': '5391990d0e0a260fb5001629', 'de...",82087155,53.0,212.0,47087155,134.534729,3.50,1.766667

### Question 1
Find the maximum profit.

In [32]:
# Write your solution here
print(df['profit'].max())

1316249360

### Question 2
Find the minimum profit.

In [33]:
# Write your solution here
print(df['profit'].min())

-107447384

### Question 3
Find the average profit.

In [34]:
# Write your solution here
print(df['profit'].mean())

44194517.77866667

### Question 4
Find the median profit.

In [35]:
# Write your solution here
print(df['profit'].median())

6121122.5

### Question 5
Find the mode of profit.

In [36]:
# Write your solution here
print(df['profit'].mode())

0    0
Name: profit, dtype: int64

### Question 6
Find the total profit generated by all movies.

In [37]:
# Write your solution here
print(df['profit'].sum())

132583553336

### Question 7
Find the maximum runtime.

In [38]:
# Write your solution here
print(df['runtime'].max())

338.0

### Question 8
Find the minimum runtime.

In [39]:
# Write your solution here
print(df['runtime'].min())

0.0

### Question 9
Find the average runtime.

In [40]:

print(df['runtime'].mean())

107.85657104736491

### Question 10
Find the movie having the highest revenue.

In [41]:
# Write your solution here
df[df['revenue']==df['revenue'].max()]

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,Keywords,cast,crew,revenue,half_runtime,double_runtime,profit,profit_percentage,budget_in_crores,runtime_hours
1126,1127,"[{'id': 86311, 'name': 'The Avengers Collectio...",220000000,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",http://marvel.com/avengers_movie/,tt0848228,en,The Avengers,When an unexpected enemy emerges and threatens...,89.887648,...,"[{'id': 242, 'name': 'new york'}, {'id': 5539,...","[{'cast_id': 46, 'character': 'Tony Stark / Ir...","[{'credit_id': '52fe4495c3a368484e02b1cf', 'de...",1519557910,71.5,286.0,1299557910,590.708141,22.0,2.383333

### Question 11
Find the movie having the lowest budget.

In [42]:
# Write your solution here
df[df['budget']==df['budget'].min()]

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,Keywords,cast,crew,revenue,half_runtime,double_runtime,profit,profit_percentage,budget_in_crores,runtime_hours
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970,59.0,236.0,3923970,inf,0.0,1.966667
7,8,NaN,0,"[{'id': 99, 'name': 'Documentary'}]",NaN,tt0391024,en,Control Room,A chronicle which provides a rare window into ...,1.949044,...,"[{'id': 917, 'name': 'journalism'}, {'id': 163...","[{'cast_id': 2, 'character': 'Himself', 'credi...","[{'credit_id': '52fe47a69251416c750a0daf', 'de...",2586511,42.0,168.0,2586511,inf,0.0,1.400000
8,9,"[{'id': 256377, 'name': 'The Muppet Collection...",0,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",NaN,tt0117110,en,Muppet Treasure Island,After telling the story of Flint's last journe...,6.902423,...,"[{'id': 2041, 'name': 'island'}, {'id': 4418, ...","[{'cast_id': 1, 'character': 'Long John Silver...","[{'credit_id': '52fe43c89251416c7501deb3', 'de...",34327391,50.0,200.0,34327391,inf,0.0,1.666667
11,12,"[{'id': 48190, 'name': 'Revenge of the Nerds C...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt0093857,en,Revenge of the Nerds II: Nerds in Paradise,The members of the Lambda Lambda Lambda frater...,10.543750,...,"[{'id': 5801, 'name': 'nerd'}, {'id': 6876, 'n...","[{'cast_id': 2, 'character': 'Lewis Skolnick',...","[{'credit_id': '52fe46f49251416c750891e9', 'de...",22642033,49.0,196.0,22642033,inf,0.0,1.633333
17,18,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",NaN,tt1700845,en,The Invisible Woman,"In 1857, at the height of his fame and fortune...",4.183558,...,"[{'id': 5565, 'name': 'biography'}, {'id': 180...","[{'cast_id': 7, 'character': 'Charles Dickens'...","[{'credit_id': '53b94a260e0a2676c7009b37', 'de...",1234254,55.5,222.0,1234254,inf,0.0,1.850000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2989,2990,NaN,0,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...",NaN,tt0206367,en,The Trumpet Of The Swan,The adventures of a young Trumpeter swan who c...,0.851599,...,"[{'id': 6653, 'name': 'trumpet'}, {'id': 10407...","[{'cast_id': 1, 'character': 'Father', 'credit...","[{'credit_id': '58bc9d609251416084044b0e', 'de...",100202,37.5,150.0,100202,inf,0.0,1.250000
2990,2991,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",NaN,tt0118663,en,B.A.P.S.,Can two clueless Georgia homegirls with big he...,1.560980,...,"[{'id': 1437, 'name': 'burglar'}, {'id': 1946,...","[{'cast_id': 3, 'character': 'Nisi', 'credit_i...","[{'credit_id': '52fe477b9251416c7509af57', 'de...",7240837,45.0,180.0,7240837,inf,0.0,1.500000
2994,2995,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,tt0105327,en,School Ties,When David Greene receives a football scholars...,7.438381,...,"[{'id': 6075, 'name': 'sport'}, {'id': 10144, ...","[{'cast_id': 2, 'character': 'David Greene', '...","[{'credit_id': '5637777ac3a3681b4d01f9f5', 'de...",14715067,53.0,212.0,14715067,inf,0.0,1.766667
2995,2996,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",NaN,tt0109403,en,Chasers,Military men Rock Reilly and Eddie Devane are ...,9.853270,...,"[{'id': 378, 'name': 'prison'}, {'id': 572, 'n...","[{'cast_id': 2, 'character': 'Rock Reilly', 'c...","[{'credit_id': '52fe4494c3a368484e02ac7d', 'de...",1596687,51.0,204.0,1596687,inf,0.0,1.700000
2996,2997,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...",NaN,tt2364975,sv,Vi är bäst!,Three girls in 1980s Stockholm decide to form ...,3.727996,...,"[{'id': 1192, 'name': 'sweden'}, {'id': 4470, ...","[{'cast_id': 5, 'character': 'Bobo', 'credit_i...","[{'credit_id': '5716b72ac3a3686678012c84', 'de...",180590,51.0,204.0,180590,inf,0.0,1.700000

### Question 1
List the top 10 movies by revenue.

In [43]:
# Write your solution here
df.sort_values(by = 'revenue',ascending = False)[['title','revenue']].head(10)

                                            title     revenue
1126                                 The Avengers  1519557910
1761                                    Furious 7  1506249360
2770                      Avengers: Age of Ultron  1405403694
684                          Beauty and the Beast  1262886337
2322               Transformers: Dark of the Moon  1123746996
906                         The Dark Knight Rises  1084939099
2135  Pirates of the Caribbean: On Stranger Tides  1045713802
2562                                 Finding Dory  1028570889
881                           Alice in Wonderland  1025491110
734                                      Zootopia  1023784195

### Question 2
List the top 10 movies by profit.

In [44]:
# Write your solution here
df.sort_values(by = 'profit',ascending = False)[['title','profit']].head(10)

                                      title      profit
1761                              Furious 7  1316249360
1126                           The Avengers  1299557910
2770                Avengers: Age of Ultron  1125403694
684                    Beauty and the Beast  1102886337
2322         Transformers: Dark of the Moon   928746996
734                                Zootopia   873784195
1735                          Jurassic Park   857100000
543   The Lord of the Rings: The Two Towers   847287400
906                   The Dark Knight Rises   834939099
2562                           Finding Dory   828570889

### Question 3
List the top 10 movies by popularity.

In [45]:
# Write your solution here
df.sort_values(by = 'popularity',ascending = False)[['title','popularity']].head(10)

                               title  popularity
518                     Wonder Woman  294.337037
684             Beauty and the Beast  287.253654
1695                     Baby Driver  228.032744
2326                        Deadpool  187.860492
2126  Guardians of the Galaxy Vol. 2  185.330992
1309                       Gone Girl  154.801009
1715  War for the Planet of the Apes  146.161786
1673                 The Dark Knight  123.167259
1126                    The Avengers   89.887648
2293                      The Circle   88.439243

### Question 4
Find the 10 longest movies.

In [46]:
# Write your solution here
df.sort_values(by='runtime',ascending=False).head(10)

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,Keywords,cast,crew,revenue,half_runtime,double_runtime,profit,profit_percentage,budget_in_crores,runtime_hours
1211,1212,NaN,18000000,"[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...",NaN,tt1321865,en,Carlos,"The story of Venezuelan revolutionary, Ilich R...",4.558075,...,"[{'id': 1419, 'name': 'gun'}, {'id': 7336, 'na...","[{'cast_id': 4, 'character': ""Ilich Ram√≠rez S...","[{'credit_id': '57352b61c3a3680253000870', 'de...",871279,169.0,676.0,-17128721,-95.159561,1.80000,5.633333
1922,1923,NaN,31115000,"[{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...",NaN,tt0056937,en,Cleopatra,Historical epic. The triumphs and tragedy of t...,8.591238,...,"[{'id': 5049, 'name': 'ancient rome'}, {'id': ...","[{'cast_id': 2, 'character': 'Cleopatra', 'cre...","[{'credit_id': '52fe4493c3a36847f809de91', 'de...",71000000,124.0,496.0,39885000,128.185762,3.11150,4.133333
523,524,NaN,13000000,"[{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...",NaN,tt0049833,en,The Ten Commandments,"Escaping death, a Hebrew infant is raised in a...",11.147040,...,"[{'id': 1160, 'name': 'egypt'}, {'id': 2618, '...","[{'cast_id': 9, 'character': 'Moses', 'credit_...","[{'credit_id': '58acab8cc3a3686f0d00093f', 'de...",122700000,110.0,440.0,109700000,843.846154,1.30000,3.666667
1302,1303,NaN,44000000,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",NaN,tt0080855,en,Heaven's Gate,Harvard graduate James Averill (Kris Kristoffe...,4.393576,...,"[{'id': 680, 'name': 'montana'}, {'id': 797, '...","[{'cast_id': 1, 'character': 'James Averill', ...","[{'credit_id': '52fe43d49251416c7501fcf7', 'de...",3484331,109.5,438.0,-40515669,-92.081066,4.40000,3.650000
1914,1915,NaN,56000000,"[{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...",NaN,tt0279111,en,Gods and Generals,The film centers mostly around the personal an...,5.374563,...,"[{'id': 6091, 'name': 'war'}, {'id': 14643, 'n...","[{'cast_id': 3, 'character': 'Lt. Gen. Thomas ...","[{'credit_id': '52fe469e9251416c7507dfbb', 'de...",12923936,107.0,428.0,-43076064,-76.921543,5.60000,3.566667
2353,2354,NaN,8376800,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://www.jodhaaakbar.com/,tt0449994,hi,Jodhaa Akbar,Jodhaa Akbar is a sixteenth century love story...,12.237488,...,"[{'id': 1157, 'name': 'wife husband relationsh...","[{'cast_id': 1, 'character': 'Jalaluddin Moham...","[{'credit_id': '52fe45c99251416c75062761', 'de...",13000000,106.5,426.0,4623200,55.190526,0.83768,3.550000
625,626,NaN,15000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",NaN,tt0052618,en,Ben-Hur,Ben-Hur is a 1959 epic film directed by Willia...,14.319743,...,"[{'id': 3035, 'name': 'roman'}, {'id': 3071, '...","[{'cast_id': 20, 'character': 'Judah Ben-Hur',...","[{'credit_id': '52fe4266c3a36847f801b99f', 'de...",146900000,106.0,424.0,131900000,879.333333,1.50000,3.533333
1975,1976,NaN,2000000,"[{'id': 35, 'name': 'Comedy'}]",http://sh-sh.ru/,tt1651118,ru,Шапито-шоу,"Four parts and four travels to the sea, four c...",0.741560,...,"[{'id': 4344, 'name': 'musical'}]","[{'cast_id': 1001, 'character': '–æ—Ç–µ—Ü', 'c...","[{'credit_id': '52fe49f69251416c910bea51', 'de...",393816,103.5,414.0,-1606184,-80.309200,0.20000,3.450000
1731,1732,NaN,3900000,"[{'id': 18, 'name': 'Drama'}, {'id': 10769, 'n...",NaN,tt0222012,ta,Hey Ram,Saketh Ram's wife is raped and killed during d...,0.562097,...,"[{'id': 441, 'name': 'assassination'}, {'id': ...","[{'cast_id': 1, 'character': 'Saket Ram', 'cre...","[{'credit_id': '52fe462cc3a368484e082aaf', 'de...",4900000,99.5,398.0,1000000,25.641026,0.39000,3.316667
2120,2121,NaN,12000000,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",NaN,tt0054331,en,Spartacus,Spartacus is a 1960 American historical drama ...,11.110376,...,"[{'id': 1394, 'name': 'gladiator'}, {'id': 140...","[{'cast_id': 21, 'character': 'Spartacus', 'cr...","[{'credit_id': '52fe4294c3a36847f8029cc9', 'de...",60000000,98.5,394.0,48000000,400.000000,1.20000,3.283333

### Question 5
Find the 10 shortest movies.

In [47]:
# Write your solution here
df.sort_values(by='runtime',ascending=False).tail(10)

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,Keywords,cast,crew,revenue,half_runtime,double_runtime,profit,profit_percentage,budget_in_crores,runtime_hours
2865,2866,"[{'id': 188197, 'name': 'Cetto La Qualunque - ...",5579750,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2456720,it,Tutto tutto niente niente,NaN,2.208906,...,"[{'id': 8201, 'name': 'satire'}, {'id': 33501,...","[{'cast_id': 1, 'character': 'Cetto La Qualunq...","[{'credit_id': '52fe4c48c3a36847f82269b9', 'de...",8927600,0.0,0.0,3347850,60.000000,0.557975,0.0
1255,1256,NaN,0,"[{'id': 37, 'name': 'Western'}]",NaN,tt0072785,it,Cipolla Colt,Onion Jack (Franco Nero) has bought a piece of...,1.623440,...,"[{'id': 156212, 'name': 'spaghetti western'}]","[{'cast_id': 14, 'character': 'Onion Stark', '...","[{'credit_id': '52fe493a9251416c750c169b', 'de...",39598448,0.0,0.0,39598448,inf,0.000000,0.0
1541,1542,NaN,750000,"[{'id': 80, 'name': 'Crime'}, {'id': 35, 'name...",NaN,tt3805180,ru,Все и сразу,NaN,0.201582,...,"[{'id': 642, 'name': 'robbery'}, {'id': 231149...","[{'cast_id': 3, 'character': 'Viktor', 'credit...","[{'credit_id': '53b7a7b90e0a2676b8006ab6', 'de...",3,0.0,0.0,-749997,-99.999600,0.075000,0.0
390,391,NaN,6843500,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2550838,it,Il peggior Natale della mia vita,NaN,3.800073,...,NaN,"[{'cast_id': 2, 'character': 'Alberto', 'credi...","[{'credit_id': '52fe4bb79251416c7510bc79', 'de...",10703234,0.0,0.0,3859734,56.400000,0.684350,0.0
2645,2646,NaN,0,"[{'id': 10749, 'name': 'Romance'}]",NaN,tt3956312,en,同桌的妳,"In the summer of 1993, timid and shy Zhou Xiao...",0.504000,...,NaN,"[{'cast_id': 0, 'character': 'Zhou Xiao Zhi', ...","[{'credit_id': '54064dd90e0a2658d800d8d9', 'de...",76000000,0.0,0.0,76000000,inf,0.000000,0.0
2498,2499,"[{'id': 106790, 'name': 'Hooked Collection', '...",3500000,"[{'id': 28, 'name': 'Action'}, {'id': 878, 'na...",NaN,tt1620549,ru,Na Igre 2. Novyy Uroven,The continuation of the adventures of the hero...,0.884241,...,NaN,"[{'cast_id': 10, 'character': 'Vampire', 'cred...","[{'credit_id': '52fe46759251416c91055281', 'de...",2294357,0.0,0.0,-1205643,-34.446943,0.350000,0.0
591,592,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",NaN,tt0768690,ru,А поутру они проснулись,NaN,0.402368,...,"[{'id': 4897, 'name': 'multiple character'}, {...","[{'cast_id': 8, 'character': '', 'credit_id': ...","[{'credit_id': '52fe4d449251416c911103f5', 'de...",234748,0.0,0.0,234748,inf,0.000000,0.0
1874,1875,NaN,0,"[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...",http://www.vt4.be/vermist,tt1133617,en,Vermist,Five members of the Missing Persons Task Force...,0.229233,...,NaN,"[{'cast_id': 2, 'character': 'Murat Hoxha', 'c...","[{'credit_id': '52fe4838c3a36847f815cef1', 'de...",1,0.0,0.0,1,inf,0.000000,0.0
1335,1336,NaN,6000000,"[{'id': 18, 'name': 'Drama'}]",NaN,tt1107828,ru,Королёв,NaN,0.292296,...,NaN,"[{'cast_id': 3, 'character': '–°–µ—Ä–≥–µ–π –ö–...","[{'credit_id': '52fe4db29251416c7513d819', 'de...",31000,NaN,NaN,-5969000,-99.483333,0.600000,NaN
2302,2303,NaN,0,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt0116485,de,Happy Weekend,NaN,0.002229,...,"[{'id': 572, 'name': 'sex'}, {'id': 596, 'name...","[{'cast_id': 0, 'character': 'Joachim Krippo',...",NaN,65335,NaN,NaN,65335,inf,0.000000,NaN

### Question 6
Find the total number of movies available in each language.

In [48]:
# Write your solution here
df['original_language'].value_counts()

original_language
en    2575
fr      78
ru      47
es      43
hi      42
ja      37
it      24
ko      20
cn      20
zh      19
de      18
ta      16
sv       8
pt       6
nl       6
fa       5
da       5
ro       4
hu       3
tr       3
no       2
te       2
pl       2
fi       2
ml       2
sr       1
cs       1
mr       1
ar       1
he       1
ur       1
el       1
vi       1
nb       1
bn       1
id       1
Name: count, dtype: int64

### Question 7
Find the language with the highest number of movies.

In [49]:
# Write your solution here
df['original_language'].value_counts().sort_values(ascending=False).head(1)

original_language
en    2575
Name: count, dtype: int64

### Question 8
Find the average runtime for each language.

In [50]:

df['average_runtime'] = df['runtime'].mean()

unique_languages_df = df[['original_language', 'average_runtime']].drop_duplicates(subset='original_language')
unique_languages_df

     original_language  average_runtime
0                   en       107.856571
3                   hi       107.856571
4                   ko       107.856571
15                  sr       107.856571
30                  fr       107.856571
45                  it       107.856571
50                  nl       107.856571
67                  zh       107.856571
71                  es       107.856571
73                  cs       107.856571
76                  ta       107.856571
87                  cn       107.856571
95                  ru       107.856571
104                 tr       107.856571
183                 ja       107.856571
195                 fa       107.856571
218                 sv       107.856571
247                 de       107.856571
276                 te       107.856571
293                 pt       107.856571
586                 mr       107.856571
661                 da       107.856571
854                 fi       107.856571
866                 el       107.856571
931                 ur       107.856571
1031                he       107.856571
1075                no       107.856571
1331                ar       107.856571
1459                nb       107.856571
1753                ro       107.856571
1757                vi       107.856571
1791                pl       107.856571
1793                hu       107.856571
2037                ml       107.856571
2224                bn       107.856571
2688                id       107.856571

### Question 9
Find the average profit for each language.

In [51]:
# Write your solution here
df

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,cast,crew,revenue,half_runtime,double_runtime,profit,profit_percentage,budget_in_crores,runtime_hours,average_runtime
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,"[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651,46.5,186.0,-1685349,-12.038207,1.40,1.550000,107.856571
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,"[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435,56.5,226.0,55149435,137.873588,4.00,1.883333,107.856571
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,"[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000,52.5,210.0,9792000,296.727273,0.33,1.750000,107.856571
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,"[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000,61.0,244.0,14800000,1233.333333,0.12,2.033333,107.856571
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970,59.0,236.0,3923970,inf,0.00,1.966667,107.856571
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,2996,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",NaN,tt0109403,en,Chasers,Military men Rock Reilly and Eddie Devane are ...,9.853270,...,"[{'cast_id': 2, 'character': 'Rock Reilly', 'c...","[{'credit_id': '52fe4494c3a368484e02ac7d', 'de...",1596687,51.0,204.0,1596687,inf,0.00,1.700000,107.856571
2996,2997,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...",NaN,tt2364975,sv,Vi är bäst!,Three girls in 1980s Stockholm decide to form ...,3.727996,...,"[{'cast_id': 5, 'character': 'Bobo', 'credit_i...","[{'credit_id': '5716b72ac3a3686678012c84', 'de...",180590,51.0,204.0,180590,inf,0.00,1.700000,107.856571
2997,2998,NaN,65000000,"[{'id': 80, 'name': 'Crime'}, {'id': 28, 'name...",NaN,tt0116908,en,The Long Kiss Goodnight,"Samantha Caine, suburban homemaker, is the ide...",14.482345,...,"[{'cast_id': 10, 'character': 'Samantha Caine ...","[{'credit_id': '52fe443a9251416c7502d579', 'de...",89456761,60.0,240.0,24456761,37.625786,6.50,2.000000,107.856571
2998,2999,NaN,42000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",http://www.alongcamepolly.com/,tt0343135,en,Along Came Polly,Reuben Feffer is a guy who's spent his entire ...,15.725542,...,"[{'cast_id': 8, 'character': 'Reuben Feffer', ...","[{'credit_id': '556f817b9251410866000a63', 'de...",171963386,45.0,180.0,129963386,309.436633,4.20,1.500000,107.856571
2999,3000,NaN,35000000,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",http://www.abductionthefilm.com/,tt1600195,en,Abduction,A young man sets out to uncover the truth abou...,10.512109,...,"[{'cast_id': 2, 'character': 'Nathan Harper', ...","[{'credit_id': '5391990d0e0a260fb5001629', 'de...",82087155,53.0,212.0,47087155,134.534729,3.50,1.766667,107.856571

### Question 1
Find the movie with the highest profit percentage.

In [52]:

# Write your solution here
df.sort_values(by='profit_percentage',ascending=False)[['original_title','profit_percentage']].head(1)

     original_title  profit_percentage
2996    Vi är bäst!                inf

### Question 2
Find movies that earned more than 5 times their budget.

In [53]:
# Write your solution here
df[df['profit']==5*df['budget']][['original_title','budget','revenue','profit']]

     original_title  budget  revenue   profit
2270   Mean Streets  500000  3000000  2500000

### Question 3
Find movies that resulted in a loss.

In [54]:
# Write your solution here
df[df['profit']<0][['original_title','budget','revenue','profit']]

                              original_title    budget   revenue    profit
0                     Hot Tub Time Machine 2  14000000  12314651  -1685349
5     Pinocchio and the Emperor of the Night   8000000   3261638  -4738362
15                                   Šišanje    500000       198   -499802
18                               Chalet Girl   8000000   1749457  -6250543
27                                   What If  11000000   7847000  -3153000
...                                      ...       ...       ...       ...
2977                              Angel Eyes  53000000  29700000 -23300000
2982                                 Smashed    500000    376597   -123403
2983                           Anna Karenina  35000000    791830 -34208170
2985                             Freedomland  37665000  14655628 -23009372
2986                               Paparazzi  20000000  16605763  -3394237

[655 rows x 4 columns]

### Question 4
Calculate the percentage of profitable movies.

In [55]:
# Write your solution here
print((df['profit']>0).mean()*100)

77.9

### Question 5
Calculate the percentage of loss-making movies.

In [56]:
# Write your solution here
print((df['profit']<0).mean()*100)

21.833333333333332

### Question 6
Find the top 5 most profitable Hindi movies.

In [64]:
# Write your solution here
df[df['original_language']=='hi'].sort_values(by='profit',ascending=False).head(5)

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,cast,crew,revenue,half_runtime,double_runtime,profit,profit_percentage,budget_in_crores,runtime_hours,average_runtime
585,586,NaN,10400000,"[{'id': 18, 'name': 'Drama'}]",NaN,tt5074352,hi,दंगल,Dangal is an extraordinary true story based on...,8.792104,...,"[{'cast_id': 0, 'character': 'Mahavir Singh Ph...","[{'credit_id': '5714ef3f92514146c80003ea', 'de...",310000000,80.5,322.0,299600000,2880.769231,1.04,2.683333,107.856571
2239,2240,"[{'id': 44976, 'name': 'Dhoom Series', 'poster...",19500000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",NaN,tt1833673,hi,धूम ३,"To avenge his father's death, a circus enterta...",5.326716,...,"[{'cast_id': 2, 'character': 'Sahir', 'credit_...","[{'credit_id': '59488707c3a36816c504b523', 'de...",91000000,86.0,344.0,71500000,366.666667,1.95,2.866667,107.856571
1572,1573,NaN,9100000,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",http://www.rememberghajini.com/,tt1166100,hi,Ghajini,Sanjay a rich tycoon suffering from short term...,4.239080,...,"[{'cast_id': 12, 'character': 'Sanjay Singhani...","[{'credit_id': '52fe45c99251416c75062659', 'de...",76000000,91.5,366.0,66900000,735.164835,0.91,3.050000,107.856571
1656,1657,NaN,18000000,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",http://www.chennaiexp2013.com/chennaiexpress.aspx,tt2112124,hi,Chennai Express,Rahul embarks on a journey to a small town in ...,4.193560,...,"[{'cast_id': 2, 'character': 'Rahul Mithaiwala...","[{'credit_id': '581e56659251410f4f00f125', 'de...",62000000,70.5,282.0,44000000,244.444444,1.80,2.350000,107.856571
1732,1733,"[{'id': 419784, 'name': 'Masti Collection', 'p...",5500000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt2476154,hi,Grand Masti,"Amar, Prem and Meet are longtime friends who h...",1.250293,...,"[{'cast_id': 2, 'character': 'Amar', 'credit_i...","[{'credit_id': '52fe4db49251416c7513dd27', 'de...",47000000,70.0,280.0,41500000,754.545455,0.55,2.333333,107.856571

### Question 7
Find the top 5 most profitable English movies.

In [66]:
# Write your solution here
# Write your solution here
df[df['original_language']=='en'].sort_values(by='profit',ascending=False).head(5)

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,cast,crew,revenue,half_runtime,double_runtime,profit,profit_percentage,budget_in_crores,runtime_hours,average_runtime
1761,1762,"[{'id': 9485, 'name': 'The Fast and the Furiou...",190000000,"[{'id': 28, 'name': 'Action'}]",http://www.furious7.com/,tt2820852,en,Furious 7,Deckard Shaw seeks revenge against Dominic Tor...,27.275687,...,"[{'cast_id': 17, 'character': 'Dominic Toretto...","[{'credit_id': '52fe4cc8c3a36847f823e681', 'de...",1506249360,68.5,274.0,1316249360,692.762821,19.0,2.283333,107.856571
1126,1127,"[{'id': 86311, 'name': 'The Avengers Collectio...",220000000,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",http://marvel.com/avengers_movie/,tt0848228,en,The Avengers,When an unexpected enemy emerges and threatens...,89.887648,...,"[{'cast_id': 46, 'character': 'Tony Stark / Ir...","[{'credit_id': '52fe4495c3a368484e02b1cf', 'de...",1519557910,71.5,286.0,1299557910,590.708141,22.0,2.383333,107.856571
2770,2771,"[{'id': 86311, 'name': 'The Avengers Collectio...",280000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://marvel.com/movies/movie/193/avengers_ag...,tt2395427,en,Avengers: Age of Ultron,When Tony Stark tries to jumpstart a dormant p...,37.379420,...,"[{'cast_id': 76, 'character': 'Tony Stark / Ir...","[{'credit_id': '55d5f7d4c3a3683e7e0016eb', 'de...",1405403694,70.5,282.0,1125403694,401.929891,28.0,2.350000,107.856571
684,685,NaN,160000000,"[{'id': 10751, 'name': 'Family'}, {'id': 14, '...",http://movies.disney.com/beauty-and-the-beast-...,tt2771200,en,Beauty and the Beast,A live-action adaptation of Disney's version o...,287.253654,...,"[{'cast_id': 174, 'character': 'Belle', 'credi...","[{'credit_id': '551879bec3a3681f840004eb', 'de...",1262886337,64.5,258.0,1102886337,689.303961,16.0,2.150000,107.856571
2322,2323,"[{'id': 8650, 'name': 'Transformers Collection...",195000000,"[{'id': 28, 'name': 'Action'}, {'id': 878, 'na...",http://www.transformersmovie.com/,tt1399103,en,Transformers: Dark of the Moon,Sam Witwicky takes his first tenuous steps int...,4.503505,...,"[{'cast_id': 3, 'character': 'Sam Witwicky', '...","[{'credit_id': '537f0b740e0a2624b40044d0', 'de...",1123746996,77.0,308.0,928746996,476.280511,19.5,2.566667,107.856571

### Question 8
Find all movies with runtime between 120 and 180 minutes.

In [67]:
# Write your solution here
df[(df['runtime']>120) & (df['runtime']<180)]

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,cast,crew,revenue,half_runtime,double_runtime,profit,profit_percentage,budget_in_crores,runtime_hours,average_runtime
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,"[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000,61.0,244.0,14800000,1233.333333,0.120000,2.033333,107.856571
12,13,NaN,15000000,"[{'id': 18, 'name': 'Drama'}]",http://www.dreamworks.com/ab/,tt0169547,en,American Beauty,"Lester Burnham, a depressed suburban father in...",20.726578,...,"[{'cast_id': 6, 'character': 'Lester Burnham',...","[{'credit_id': '52fe420ec3a36847f80007c5', 'de...",356296601,61.0,244.0,341296601,2275.310673,1.500000,2.033333,107.856571
14,15,NaN,102000000,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt0181689,en,Minority Report,John Anderton is a top 'Precrime' cop in the l...,20.666063,...,"[{'cast_id': 5, 'character': 'Chief John Ander...","[{'credit_id': '52fe4223c3a36847f8006f3d', 'de...",358372926,72.5,290.0,256372926,251.346006,10.200000,2.416667,107.856571
20,21,NaN,80000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 10751...",NaN,tt0120738,en,Lost in Space,The prospects for continuing life on Earth in ...,12.000579,...,"[{'cast_id': 26, 'character': 'Dr. Zachary Smi...","[{'credit_id': '52fe433bc3a36847f80448b9', 'de...",136159423,65.0,260.0,56159423,70.199279,8.000000,2.166667,107.856571
33,34,"[{'id': 207632, 'name': 'The ABCs of Death Col...",0,"[{'id': 27, 'name': 'Horror'}]",NaN,tt2926810,en,ABCs of Death 2,Taking all that was great from the first insta...,8.254856,...,"[{'cast_id': 60, 'character': 'Assassin (Segme...","[{'credit_id': '52fe4cd69251416c91101d73', 'de...",7171,62.5,250.0,7171,inf,0.000000,2.083333,107.856571
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2969,2970,NaN,19800000,"[{'id': 18, 'name': 'Drama'}, {'id': 9648, 'na...",NaN,tt0280707,en,Gosford Park,"Multiple storylined drama set in 1932, showing...",14.101101,...,"[{'cast_id': 2, 'character': 'Mrs. Wilson', 'c...","[{'credit_id': '52fe4401c3a36847f807ceab', 'de...",87754044,68.5,274.0,67954044,343.202242,1.980000,2.283333,107.856571
2970,2971,NaN,25000000,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",NaN,tt0103855,en,The Bodyguard,A former Secret Service agent grudgingly takes...,9.805017,...,"[{'cast_id': 17, 'character': 'Rachel Marron',...","[{'credit_id': '52fe425ec3a36847f8019133', 'de...",411006740,64.5,258.0,386006740,1544.026960,2.500000,2.150000,107.856571
2980,2981,NaN,300000,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",https://www.facebook.com/Actionherobiju/,tt5320514,ml,ആക്ഷൻ ഹീറോ ബിജു,Biju is an honest policeman who fights the inj...,0.350207,...,"[{'cast_id': 1, 'character': 'Sub-Inspector Bi...","[{'credit_id': '56b4d47f92514112b90045f6', 'de...",2500000,72.0,288.0,2200000,733.333333,0.030000,2.400000,107.856571
2992,2993,NaN,1135654,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",NaN,tt0015400,en,The Thief of Bagdad,A recalcitrant thief vies with a duplicitous M...,3.878515,...,"[{'cast_id': 3, 'character': 'The Thief of Bag...","[{'credit_id': '52fe45bec3a368484e06c70b', 'de...",1213880,74.5,298.0,78226,6.888190,0.113565,2.483333,107.856571
2993,2994,NaN,60000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",http://www.theterminal-themovie.com/,tt0362227,en,The Terminal,Viktor Navorski is a man without a country; hi...,14.092373,...,"[{'cast_id': 4, 'character': 'Viktor Navorski'...","[{'credit_id': '52fe4259c3a36847f8017699', 'de...",219417255,64.0,256.0,159417255,265.695425,6.000000,2.133333,107.856571

### Question 9
Find movies with revenue greater than 1 billion.

In [68]:
df[df['revenue']>1000000000]
# Write your solution here

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,cast,crew,revenue,half_runtime,double_runtime,profit,profit_percentage,budget_in_crores,runtime_hours,average_runtime
684,685,NaN,160000000,"[{'id': 10751, 'name': 'Family'}, {'id': 14, '...",http://movies.disney.com/beauty-and-the-beast-...,tt2771200,en,Beauty and the Beast,A live-action adaptation of Disney's version o...,287.253654,...,"[{'cast_id': 174, 'character': 'Belle', 'credi...","[{'credit_id': '551879bec3a3681f840004eb', 'de...",1262886337,64.5,258.0,1102886337,689.303961,16.0,2.150000,107.856571
734,735,NaN,150000000,"[{'id': 16, 'name': 'Animation'}, {'id': 12, '...",http://movies.disney.com/zootopia,tt2948356,en,Zootopia,"Determined to prove herself, Officer Judy Hopp...",26.024868,...,"[{'cast_id': 23, 'character': 'Judy Hopps (voi...","[{'credit_id': '536e09650e0a2647cb00fe6b', 'de...",1023784195,54.0,216.0,873784195,582.522797,15.0,1.800000,107.856571
881,882,"[{'id': 261307, 'name': 'Alice in Wonderland C...",200000000,"[{'id': 10751, 'name': 'Family'}, {'id': 14, '...",http://disney.go.com/wonderland/,tt1014759,en,Alice in Wonderland,"Alice, an unpretentious and individual 19-year...",17.285093,...,"[{'cast_id': 7, 'character': 'Alice Kingsleigh...","[{'credit_id': '52fe44c09251416c7503fbc3', 'de...",1025491110,54.0,216.0,825491110,412.745555,20.0,1.800000,107.856571
906,907,"[{'id': 263, 'name': 'The Dark Knight Collecti...",250000000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",http://www.thedarkknightrises.com/,tt1345836,en,The Dark Knight Rises,Following the death of District Attorney Harve...,20.582580,...,NaN,NaN,1084939099,82.5,330.0,834939099,333.975640,25.0,2.750000,107.856571
1126,1127,"[{'id': 86311, 'name': 'The Avengers Collectio...",220000000,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",http://marvel.com/avengers_movie/,tt0848228,en,The Avengers,When an unexpected enemy emerges and threatens...,89.887648,...,"[{'cast_id': 46, 'character': 'Tony Stark / Ir...","[{'credit_id': '52fe4495c3a368484e02b1cf', 'de...",1519557910,71.5,286.0,1299557910,590.708141,22.0,2.383333,107.856571
1673,1674,"[{'id': 263, 'name': 'The Dark Knight Collecti...",185000000,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...",http://thedarkknight.warnerbros.com/dvdsite/,tt0468569,en,The Dark Knight,Batman raises the stakes in his war on crime. ...,123.167259,...,"[{'cast_id': 35, 'character': 'Bruce Wayne / B...","[{'credit_id': '55a0eb4a925141296b0010f8', 'de...",1004558444,76.0,304.0,819558444,443.004564,18.5,2.533333,107.856571
1761,1762,"[{'id': 9485, 'name': 'The Fast and the Furiou...",190000000,"[{'id': 28, 'name': 'Action'}]",http://www.furious7.com/,tt2820852,en,Furious 7,Deckard Shaw seeks revenge against Dominic Tor...,27.275687,...,"[{'cast_id': 17, 'character': 'Dominic Toretto...","[{'credit_id': '52fe4cc8c3a36847f823e681', 'de...",1506249360,68.5,274.0,1316249360,692.762821,19.0,2.283333,107.856571
2135,2136,"[{'id': 295, 'name': 'Pirates of the Caribbean...",380000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",http://disney.go.com/pirates/index-on-stranger...,tt1298650,en,Pirates of the Caribbean: On Stranger Tides,Captain Jack Sparrow crosses paths with a woma...,27.887720,...,"[{'cast_id': 15, 'character': 'Captain Jack Sp...","[{'credit_id': '566b4f54c3a3683f56005151', 'de...",1045713802,68.0,272.0,665713802,175.187843,38.0,2.266667,107.856571
2322,2323,"[{'id': 8650, 'name': 'Transformers Collection...",195000000,"[{'id': 28, 'name': 'Action'}, {'id': 878, 'na...",http://www.transformersmovie.com/,tt1399103,en,Transformers: Dark of the Moon,Sam Witwicky takes his first tenuous steps int...,4.503505,...,"[{'cast_id': 3, 'character': 'Sam Witwicky', '...","[{'credit_id': '537f0b740e0a2624b40044d0', 'de...",1123746996,77.0,308.0,928746996,476.280511,19.5,2.566667,107.856571
2532,2533,"[{'id': 121938, 'name': 'The Hobbit Collection...",250000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",http://www.thehobbit.com/,tt0903624,en,The Hobbit: An Unexpected Journey,"Bilbo Baggins, a hobbit enjoying his quiet lif...",23.253089,...,"[{'cast_id': 6, 'character': 'Gandalf', 'credi...","[{'credit_id': '52fe4783c3a36847f8139f7f', 'de...",1021103568,84.5,338.0,771103568,308.441427,25.0,2.816667,107.856571
2562,2563,"[{'id': 137697, 'name': 'Finding Nemo Collecti...",200000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 16, '...",http://movies.disney.com/finding-dory,tt2277860,en,Finding Dory,Dory is reunited with her friends Nemo and Mar...,14.477677,...,"[{'cast_id': 2, 'character': 'Dory (voice)', '...","[{'credit_id': '55eb2fbb92514106d60041ab', 'de...",1028570889,48.5,194.0,828570889,414.285445,20.0,1.616667,107.856571
2770,2771,"[{'id': 86311, 'name': 'The Avengers Collectio...",280000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://marvel.com/movies/movie/193/avengers_ag...,tt2395427,en,Avengers: Age of Ultron,When Tony Stark tries to jumpstart a dormant p...,37.379420,...,"[{'cast_id': 76, 'character': 'Tony Stark / Ir...","[{'credit_id': '55d5f7d4c3a3683e7e0016eb', 'de...",1405403694,70.5,282.0,1125403694,401.929891,28.0,2.350000,107.856571

### Question 10
Create a report showing Total Movies, Average Budget, Average Revenue, Average Profit, Maximum Profit, Minimum Profit.

In [69]:
# Write your solution here
df1 = df.groupby('original_language')['runtime'].mean()
df1

original_language
ar     98.000000
bn    125.000000
cn    105.450000
cs     90.000000
da    105.400000
de    122.294118
el     91.000000
en    106.984078
es    100.372093
fa     96.400000
fi    100.000000
fr    106.294872
he     90.000000
hi    148.880952
hu    126.000000
id    150.000000
it     91.625000
ja    112.972973
ko    115.100000
ml    137.000000
mr    162.000000
nb    103.000000
nl    107.333333
no     95.500000
pl     99.000000
pt    114.666667
ro    108.750000
ru     95.586957
sr     97.000000
sv    122.375000
ta    159.875000
te    146.000000
tr    119.000000
ur     94.000000
vi    135.000000
zh    121.368421
Name: runtime, dtype: float64

### Question 11
Create a final summary dashboard using Pandas.

In [70]:
# Write your solution here
df1 = df.groupby('original_language')['profit'].mean()
df1

original_language
ar    1.347747e+06
bn    5.363640e+05
cn    2.289881e+07
cs    1.739300e+04
da    8.557093e+06
de    1.641414e+07
el    7.849000e+06
en    4.931629e+07
es    6.874230e+06
fa    6.761852e+05
fi   -5.263340e+05
fr    9.643460e+06
he    9.125849e+06
hi    1.863042e+07
hu   -6.085407e+05
id   -1.872791e+06
it    1.286771e+07
ja    2.344045e+07
ko    9.347554e+06
ml    1.105000e+06
mr    2.900000e+06
nb    6.596780e+05
nl    1.066334e+06
no    6.110675e+05
pl    1.133119e+07
pt   -1.714683e+06
ro   -4.903502e+05
ru    3.869827e+06
sr   -4.998020e+05
sv    1.075551e+07
ta    9.987754e+06
te    6.642485e+06
tr    5.149674e+07
ur    5.019860e+05
vi   -6.610000e+05
zh    5.096795e+07
Name: profit, dtype: float64